"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309CombinePackageRequestBody = void 0;
var Fulfillment202309CombinePackageRequestBody = /** @class */ (function () {
    function Fulfillment202309CombinePackageRequestBody() {
    }
    Fulfillment202309CombinePackageRequestBody.getAttributeTypeMap = function () {
        return Fulfillment202309CombinePackageRequestBody.attributeTypeMap;
    };
    Fulfillment202309CombinePackageRequestBody.discriminator = undefined;
    Fulfillment202309CombinePackageRequestBody.attributeTypeMap = [
        {
            "name": "combinablePackages",
            "baseName": "combinable_packages",
            "type": "Array<Fulfillment202309CombinePackageRequestBodyCombinablePackages>"
        }
    ];
    return Fulfillment202309CombinePackageRequestBody;
}());
exports.Fulfillment202309CombinePackageRequestBody = Fulfillment202309CombinePackageRequestBody;
