"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309CombinePackageResponseData = void 0;
var Fulfillment202309CombinePackageResponseData = /** @class */ (function () {
    function Fulfillment202309CombinePackageResponseData() {
    }
    Fulfillment202309CombinePackageResponseData.getAttributeTypeMap = function () {
        return Fulfillment202309CombinePackageResponseData.attributeTypeMap;
    };
    Fulfillment202309CombinePackageResponseData.discriminator = undefined;
    Fulfillment202309CombinePackageResponseData.attributeTypeMap = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<Fulfillment202309CombinePackageResponseDataErrors>"
        },
        {
            "name": "packages",
            "baseName": "packages",
            "type": "Array<Fulfillment202309CombinePackageResponseDataPackages>"
        }
    ];
    return Fulfillment202309CombinePackageResponseData;
}());
exports.Fulfillment202309CombinePackageResponseData = Fulfillment202309CombinePackageResponseData;
