"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309CreatePackagesResponseDataShippingServiceInfo = void 0;
var Fulfillment202309CreatePackagesResponseDataShippingServiceInfo = /** @class */ (function () {
    function Fulfillment202309CreatePackagesResponseDataShippingServiceInfo() {
    }
    Fulfillment202309CreatePackagesResponseDataShippingServiceInfo.getAttributeTypeMap = function () {
        return Fulfillment202309CreatePackagesResponseDataShippingServiceInfo.attributeTypeMap;
    };
    Fulfillment202309CreatePackagesResponseDataShippingServiceInfo.discriminator = undefined;
    Fulfillment202309CreatePackagesResponseDataShippingServiceInfo.attributeTypeMap = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "earliestDeliveryDays",
            "baseName": "earliest_delivery_days",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "latestDeliveryDays",
            "baseName": "latest_delivery_days",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "string"
        },
        {
            "name": "shippingProviderId",
            "baseName": "shipping_provider_id",
            "type": "string"
        },
        {
            "name": "shippingProviderName",
            "baseName": "shipping_provider_name",
            "type": "string"
        }
    ];
    return Fulfillment202309CreatePackagesResponseDataShippingServiceInfo;
}());
exports.Fulfillment202309CreatePackagesResponseDataShippingServiceInfo = Fulfillment202309CreatePackagesResponseDataShippingServiceInfo;
