"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309CreatePackagesResponse = void 0;
var Fulfillment202309CreatePackagesResponse = /** @class */ (function () {
    function Fulfillment202309CreatePackagesResponse() {
    }
    Fulfillment202309CreatePackagesResponse.getAttributeTypeMap = function () {
        return Fulfillment202309CreatePackagesResponse.attributeTypeMap;
    };
    Fulfillment202309CreatePackagesResponse.discriminator = undefined;
    Fulfillment202309CreatePackagesResponse.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Fulfillment202309CreatePackagesResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }
    ];
    return Fulfillment202309CreatePackagesResponse;
}());
exports.Fulfillment202309CreatePackagesResponse = Fulfillment202309CreatePackagesResponse;
