"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309CreatePackagesRequestBodyWeight = void 0;
var Fulfillment202309CreatePackagesRequestBodyWeight = /** @class */ (function () {
    function Fulfillment202309CreatePackagesRequestBodyWeight() {
    }
    Fulfillment202309CreatePackagesRequestBodyWeight.getAttributeTypeMap = function () {
        return Fulfillment202309CreatePackagesRequestBodyWeight.attributeTypeMap;
    };
    Fulfillment202309CreatePackagesRequestBodyWeight.discriminator = undefined;
    Fulfillment202309CreatePackagesRequestBodyWeight.attributeTypeMap = [
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }
    ];
    return Fulfillment202309CreatePackagesRequestBodyWeight;
}());
exports.Fulfillment202309CreatePackagesRequestBodyWeight = Fulfillment202309CreatePackagesRequestBodyWeight;
