"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309GetEligibleShippingServiceResponseDataDimension = void 0;
var Fulfillment202309GetEligibleShippingServiceResponseDataDimension = /** @class */ (function () {
    function Fulfillment202309GetEligibleShippingServiceResponseDataDimension() {
    }
    Fulfillment202309GetEligibleShippingServiceResponseDataDimension.getAttributeTypeMap = function () {
        return Fulfillment202309GetEligibleShippingServiceResponseDataDimension.attributeTypeMap;
    };
    Fulfillment202309GetEligibleShippingServiceResponseDataDimension.discriminator = undefined;
    Fulfillment202309GetEligibleShippingServiceResponseDataDimension.attributeTypeMap = [
        {
            "name": "height",
            "baseName": "height",
            "type": "string"
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "string"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "string"
        }
    ];
    return Fulfillment202309GetEligibleShippingServiceResponseDataDimension;
}());
exports.Fulfillment202309GetEligibleShippingServiceResponseDataDimension = Fulfillment202309GetEligibleShippingServiceResponseDataDimension;
