"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309GetOrderSplitAttributesResponseData = void 0;
var Fulfillment202309GetOrderSplitAttributesResponseData = /** @class */ (function () {
    function Fulfillment202309GetOrderSplitAttributesResponseData() {
    }
    Fulfillment202309GetOrderSplitAttributesResponseData.getAttributeTypeMap = function () {
        return Fulfillment202309GetOrderSplitAttributesResponseData.attributeTypeMap;
    };
    Fulfillment202309GetOrderSplitAttributesResponseData.discriminator = undefined;
    Fulfillment202309GetOrderSplitAttributesResponseData.attributeTypeMap = [
        {
            "name": "splitAttributes",
            "baseName": "split_attributes",
            "type": "Array<Fulfillment202309GetOrderSplitAttributesResponseDataSplitAttributes>"
        }
    ];
    return Fulfillment202309GetOrderSplitAttributesResponseData;
}());
exports.Fulfillment202309GetOrderSplitAttributesResponseData = Fulfillment202309GetOrderSplitAttributesResponseData;
