"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309GetPackageDetailResponseDataWeight = void 0;
var Fulfillment202309GetPackageDetailResponseDataWeight = /** @class */ (function () {
    function Fulfillment202309GetPackageDetailResponseDataWeight() {
    }
    Fulfillment202309GetPackageDetailResponseDataWeight.getAttributeTypeMap = function () {
        return Fulfillment202309GetPackageDetailResponseDataWeight.attributeTypeMap;
    };
    Fulfillment202309GetPackageDetailResponseDataWeight.discriminator = undefined;
    Fulfillment202309GetPackageDetailResponseDataWeight.attributeTypeMap = [
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }
    ];
    return Fulfillment202309GetPackageDetailResponseDataWeight;
}());
exports.Fulfillment202309GetPackageDetailResponseDataWeight = Fulfillment202309GetPackageDetailResponseDataWeight;
