"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309GetPackageShippingDocumentResponseData = void 0;
var Fulfillment202309GetPackageShippingDocumentResponseData = /** @class */ (function () {
    function Fulfillment202309GetPackageShippingDocumentResponseData() {
    }
    Fulfillment202309GetPackageShippingDocumentResponseData.getAttributeTypeMap = function () {
        return Fulfillment202309GetPackageShippingDocumentResponseData.attributeTypeMap;
    };
    Fulfillment202309GetPackageShippingDocumentResponseData.discriminator = undefined;
    Fulfillment202309GetPackageShippingDocumentResponseData.attributeTypeMap = [
        {
            "name": "docUrl",
            "baseName": "doc_url",
            "type": "string"
        },
        {
            "name": "trackingNumber",
            "baseName": "tracking_number",
            "type": "string"
        }
    ];
    return Fulfillment202309GetPackageShippingDocumentResponseData;
}());
exports.Fulfillment202309GetPackageShippingDocumentResponseData = Fulfillment202309GetPackageShippingDocumentResponseData;
