"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309GetPackageHandoverTimeSlotsResponseData = void 0;
var Fulfillment202309GetPackageHandoverTimeSlotsResponseData = /** @class */ (function () {
    function Fulfillment202309GetPackageHandoverTimeSlotsResponseData() {
    }
    Fulfillment202309GetPackageHandoverTimeSlotsResponseData.getAttributeTypeMap = function () {
        return Fulfillment202309GetPackageHandoverTimeSlotsResponseData.attributeTypeMap;
    };
    Fulfillment202309GetPackageHandoverTimeSlotsResponseData.discriminator = undefined;
    Fulfillment202309GetPackageHandoverTimeSlotsResponseData.attributeTypeMap = [
        {
            "name": "canDropOff",
            "baseName": "can_drop_off",
            "type": "boolean"
        },
        {
            "name": "canPickup",
            "baseName": "can_pickup",
            "type": "boolean"
        },
        {
            "name": "canVanCollection",
            "baseName": "can_van_collection",
            "type": "boolean"
        },
        {
            "name": "dropOffPointUrl",
            "baseName": "drop_off_point_url",
            "type": "string"
        },
        {
            "name": "pickupSlots",
            "baseName": "pickup_slots",
            "type": "Array<Fulfillment202309GetPackageHandoverTimeSlotsResponseDataPickupSlots>"
        }
    ];
    return Fulfillment202309GetPackageHandoverTimeSlotsResponseData;
}());
exports.Fulfillment202309GetPackageHandoverTimeSlotsResponseData = Fulfillment202309GetPackageHandoverTimeSlotsResponseData;
