"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309GetPackageDetailResponseDataDimension = void 0;
var Fulfillment202309GetPackageDetailResponseDataDimension = /** @class */ (function () {
    function Fulfillment202309GetPackageDetailResponseDataDimension() {
    }
    Fulfillment202309GetPackageDetailResponseDataDimension.getAttributeTypeMap = function () {
        return Fulfillment202309GetPackageDetailResponseDataDimension.attributeTypeMap;
    };
    Fulfillment202309GetPackageDetailResponseDataDimension.discriminator = undefined;
    Fulfillment202309GetPackageDetailResponseDataDimension.attributeTypeMap = [
        {
            "name": "height",
            "baseName": "height",
            "type": "string"
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "string"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "string"
        }
    ];
    return Fulfillment202309GetPackageDetailResponseDataDimension;
}());
exports.Fulfillment202309GetPackageDetailResponseDataDimension = Fulfillment202309GetPackageDetailResponseDataDimension;
