"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309GetTrackingResponseDataTracking = void 0;
var Fulfillment202309GetTrackingResponseDataTracking = /** @class */ (function () {
    function Fulfillment202309GetTrackingResponseDataTracking() {
    }
    Fulfillment202309GetTrackingResponseDataTracking.getAttributeTypeMap = function () {
        return Fulfillment202309GetTrackingResponseDataTracking.attributeTypeMap;
    };
    Fulfillment202309GetTrackingResponseDataTracking.discriminator = undefined;
    Fulfillment202309GetTrackingResponseDataTracking.attributeTypeMap = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "updateTimeMillis",
            "baseName": "update_time_millis",
            "type": "number"
        }
    ];
    return Fulfillment202309GetTrackingResponseDataTracking;
}());
exports.Fulfillment202309GetTrackingResponseDataTracking = Fulfillment202309GetTrackingResponseDataTracking;
