"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309MarkPackageAsShippedResponseDataWarning = void 0;
var Fulfillment202309MarkPackageAsShippedResponseDataWarning = /** @class */ (function () {
    function Fulfillment202309MarkPackageAsShippedResponseDataWarning() {
    }
    Fulfillment202309MarkPackageAsShippedResponseDataWarning.getAttributeTypeMap = function () {
        return Fulfillment202309MarkPackageAsShippedResponseDataWarning.attributeTypeMap;
    };
    Fulfillment202309MarkPackageAsShippedResponseDataWarning.discriminator = undefined;
    Fulfillment202309MarkPackageAsShippedResponseDataWarning.attributeTypeMap = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }
    ];
    return Fulfillment202309MarkPackageAsShippedResponseDataWarning;
}());
exports.Fulfillment202309MarkPackageAsShippedResponseDataWarning = Fulfillment202309MarkPackageAsShippedResponseDataWarning;
