"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309SchedulePackageHandoverRequestBody = void 0;
var Fulfillment202309SchedulePackageHandoverRequestBody = /** @class */ (function () {
    function Fulfillment202309SchedulePackageHandoverRequestBody() {
    }
    Fulfillment202309SchedulePackageHandoverRequestBody.getAttributeTypeMap = function () {
        return Fulfillment202309SchedulePackageHandoverRequestBody.attributeTypeMap;
    };
    Fulfillment202309SchedulePackageHandoverRequestBody.discriminator = undefined;
    Fulfillment202309SchedulePackageHandoverRequestBody.attributeTypeMap = [
        {
            "name": "handoverMethod",
            "baseName": "handover_method",
            "type": "string"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        },
        {
            "name": "orderLineItemIds",
            "baseName": "order_line_item_ids",
            "type": "Array<string>"
        },
        {
            "name": "pickupSlot",
            "baseName": "pickup_slot",
            "type": "Fulfillment202309SchedulePackageHandoverRequestBodyPickupSlot"
        }
    ];
    return Fulfillment202309SchedulePackageHandoverRequestBody;
}());
exports.Fulfillment202309SchedulePackageHandoverRequestBody = Fulfillment202309SchedulePackageHandoverRequestBody;
