"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309SearchPackageResponseData = void 0;
var Fulfillment202309SearchPackageResponseData = /** @class */ (function () {
    function Fulfillment202309SearchPackageResponseData() {
    }
    Fulfillment202309SearchPackageResponseData.getAttributeTypeMap = function () {
        return Fulfillment202309SearchPackageResponseData.attributeTypeMap;
    };
    Fulfillment202309SearchPackageResponseData.discriminator = undefined;
    Fulfillment202309SearchPackageResponseData.attributeTypeMap = [
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "packages",
            "baseName": "packages",
            "type": "Array<Fulfillment202309SearchPackageResponseDataPackages>"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }
    ];
    return Fulfillment202309SearchPackageResponseData;
}());
exports.Fulfillment202309SearchPackageResponseData = Fulfillment202309SearchPackageResponseData;
