"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309SearchPackageResponseDataPackagesOrders = void 0;
var Fulfillment202309SearchPackageResponseDataPackagesOrders = /** @class */ (function () {
    function Fulfillment202309SearchPackageResponseDataPackagesOrders() {
    }
    Fulfillment202309SearchPackageResponseDataPackagesOrders.getAttributeTypeMap = function () {
        return Fulfillment202309SearchPackageResponseDataPackagesOrders.attributeTypeMap;
    };
    Fulfillment202309SearchPackageResponseDataPackagesOrders.discriminator = undefined;
    Fulfillment202309SearchPackageResponseDataPackagesOrders.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "skus",
            "baseName": "skus",
            "type": "Array<Fulfillment202309SearchPackageResponseDataPackagesOrdersSkus>"
        }
    ];
    return Fulfillment202309SearchPackageResponseDataPackagesOrders;
}());
exports.Fulfillment202309SearchPackageResponseDataPackagesOrders = Fulfillment202309SearchPackageResponseDataPackagesOrders;
