"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309ShipPackageRequestBody = void 0;
var Fulfillment202309ShipPackageRequestBody = /** @class */ (function () {
    function Fulfillment202309ShipPackageRequestBody() {
    }
    Fulfillment202309ShipPackageRequestBody.getAttributeTypeMap = function () {
        return Fulfillment202309ShipPackageRequestBody.attributeTypeMap;
    };
    Fulfillment202309ShipPackageRequestBody.discriminator = undefined;
    Fulfillment202309ShipPackageRequestBody.attributeTypeMap = [
        {
            "name": "handoverMethod",
            "baseName": "handover_method",
            "type": "string"
        },
        {
            "name": "pickupSlot",
            "baseName": "pickup_slot",
            "type": "Fulfillment202309ShipPackageRequestBodyPickupSlot"
        },
        {
            "name": "selfShipment",
            "baseName": "self_shipment",
            "type": "Fulfillment202309ShipPackageRequestBodySelfShipment"
        }
    ];
    return Fulfillment202309ShipPackageRequestBody;
}());
exports.Fulfillment202309ShipPackageRequestBody = Fulfillment202309ShipPackageRequestBody;
