"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309SplitOrdersResponseDataPackages = void 0;
var Fulfillment202309SplitOrdersResponseDataPackages = /** @class */ (function () {
    function Fulfillment202309SplitOrdersResponseDataPackages() {
    }
    Fulfillment202309SplitOrdersResponseDataPackages.getAttributeTypeMap = function () {
        return Fulfillment202309SplitOrdersResponseDataPackages.attributeTypeMap;
    };
    Fulfillment202309SplitOrdersResponseDataPackages.discriminator = undefined;
    Fulfillment202309SplitOrdersResponseDataPackages.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "splittableGroupId",
            "baseName": "splittable_group_id",
            "type": "string"
        }
    ];
    return Fulfillment202309SplitOrdersResponseDataPackages;
}());
exports.Fulfillment202309SplitOrdersResponseDataPackages = Fulfillment202309SplitOrdersResponseDataPackages;
