"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309UncombinePackagesRequestBody = void 0;
var Fulfillment202309UncombinePackagesRequestBody = /** @class */ (function () {
    function Fulfillment202309UncombinePackagesRequestBody() {
    }
    Fulfillment202309UncombinePackagesRequestBody.getAttributeTypeMap = function () {
        return Fulfillment202309UncombinePackagesRequestBody.attributeTypeMap;
    };
    Fulfillment202309UncombinePackagesRequestBody.discriminator = undefined;
    Fulfillment202309UncombinePackagesRequestBody.attributeTypeMap = [
        {
            "name": "orderIds",
            "baseName": "order_ids",
            "type": "Array<string>"
        }
    ];
    return Fulfillment202309UncombinePackagesRequestBody;
}());
exports.Fulfillment202309UncombinePackagesRequestBody = Fulfillment202309UncombinePackagesRequestBody;
