"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309UncombinePackagesResponseData = void 0;
var Fulfillment202309UncombinePackagesResponseData = /** @class */ (function () {
    function Fulfillment202309UncombinePackagesResponseData() {
    }
    Fulfillment202309UncombinePackagesResponseData.getAttributeTypeMap = function () {
        return Fulfillment202309UncombinePackagesResponseData.attributeTypeMap;
    };
    Fulfillment202309UncombinePackagesResponseData.discriminator = undefined;
    Fulfillment202309UncombinePackagesResponseData.attributeTypeMap = [
        {
            "name": "packages",
            "baseName": "packages",
            "type": "Array<Fulfillment202309UncombinePackagesResponseDataPackages>"
        }
    ];
    return Fulfillment202309UncombinePackagesResponseData;
}());
exports.Fulfillment202309UncombinePackagesResponseData = Fulfillment202309UncombinePackagesResponseData;
