"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202309UpdatePackageDeliveryStatusResponseDataErrors = void 0;
var Fulfillment202309UpdatePackageDeliveryStatusResponseDataErrors = /** @class */ (function () {
    function Fulfillment202309UpdatePackageDeliveryStatusResponseDataErrors() {
    }
    Fulfillment202309UpdatePackageDeliveryStatusResponseDataErrors.getAttributeTypeMap = function () {
        return Fulfillment202309UpdatePackageDeliveryStatusResponseDataErrors.attributeTypeMap;
    };
    Fulfillment202309UpdatePackageDeliveryStatusResponseDataErrors.discriminator = undefined;
    Fulfillment202309UpdatePackageDeliveryStatusResponseDataErrors.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "Fulfillment202309UpdatePackageDeliveryStatusResponseDataErrorsDetail"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }
    ];
    return Fulfillment202309UpdatePackageDeliveryStatusResponseDataErrors;
}());
exports.Fulfillment202309UpdatePackageDeliveryStatusResponseDataErrors = Fulfillment202309UpdatePackageDeliveryStatusResponseDataErrors;
