"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202407ListingSchemasResponse = void 0;
var Product202407ListingSchemasResponse = /** @class */ (function () {
    function Product202407ListingSchemasResponse() {
    }
    Product202407ListingSchemasResponse.getAttributeTypeMap = function () {
        return Product202407ListingSchemasResponse.attributeTypeMap;
    };
    Product202407ListingSchemasResponse.discriminator = undefined;
    Product202407ListingSchemasResponse.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Product202407ListingSchemasResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }
    ];
    return Product202407ListingSchemasResponse;
}());
exports.Product202407ListingSchemasResponse = Product202407ListingSchemasResponse;
