"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202407ListingSchemasResponseDataListingSchemasFieldsRules = void 0;
var Product202407ListingSchemasResponseDataListingSchemasFieldsRules = /** @class */ (function () {
    function Product202407ListingSchemasResponseDataListingSchemasFieldsRules() {
    }
    Product202407ListingSchemasResponseDataListingSchemasFieldsRules.getAttributeTypeMap = function () {
        return Product202407ListingSchemasResponseDataListingSchemasFieldsRules.attributeTypeMap;
    };
    Product202407ListingSchemasResponseDataListingSchemasFieldsRules.discriminator = undefined;
    Product202407ListingSchemasResponseDataListingSchemasFieldsRules.attributeTypeMap = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }
    ];
    return Product202407ListingSchemasResponseDataListingSchemasFieldsRules;
}());
exports.Product202407ListingSchemasResponseDataListingSchemasFieldsRules = Product202407ListingSchemasResponseDataListingSchemasFieldsRules;
