"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202407SearchSizeChartsResponseDataSizeChartImages = void 0;
var Product202407SearchSizeChartsResponseDataSizeChartImages = /** @class */ (function () {
    function Product202407SearchSizeChartsResponseDataSizeChartImages() {
    }
    Product202407SearchSizeChartsResponseDataSizeChartImages.getAttributeTypeMap = function () {
        return Product202407SearchSizeChartsResponseDataSizeChartImages.attributeTypeMap;
    };
    Product202407SearchSizeChartsResponseDataSizeChartImages.discriminator = undefined;
    Product202407SearchSizeChartsResponseDataSizeChartImages.attributeTypeMap = [
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string"
        },
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }
    ];
    return Product202407SearchSizeChartsResponseDataSizeChartImages;
}());
exports.Product202407SearchSizeChartsResponseDataSizeChartImages = Product202407SearchSizeChartsResponseDataSizeChartImages;
