"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202407SearchSizeChartsResponse = void 0;
var Product202407SearchSizeChartsResponse = /** @class */ (function () {
    function Product202407SearchSizeChartsResponse() {
    }
    Product202407SearchSizeChartsResponse.getAttributeTypeMap = function () {
        return Product202407SearchSizeChartsResponse.attributeTypeMap;
    };
    Product202407SearchSizeChartsResponse.discriminator = undefined;
    Product202407SearchSizeChartsResponse.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Product202407SearchSizeChartsResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }
    ];
    return Product202407SearchSizeChartsResponse;
}());
exports.Product202407SearchSizeChartsResponse = Product202407SearchSizeChartsResponse;
