"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.ReturnRefund202309ApproveReturnResponse = void 0;
var ReturnRefund202309ApproveReturnResponse = /** @class */ (function () {
    function ReturnRefund202309ApproveReturnResponse() {
    }
    ReturnRefund202309ApproveReturnResponse.getAttributeTypeMap = function () {
        return ReturnRefund202309ApproveReturnResponse.attributeTypeMap;
    };
    ReturnRefund202309ApproveReturnResponse.discriminator = undefined;
    ReturnRefund202309ApproveReturnResponse.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "object"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }
    ];
    return ReturnRefund202309ApproveReturnResponse;
}());
exports.ReturnRefund202309ApproveReturnResponse = ReturnRefund202309ApproveReturnResponse;
