"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.ReturnRefund202309CalculateRefundResponseData = void 0;
var ReturnRefund202309CalculateRefundResponseData = /** @class */ (function () {
    function ReturnRefund202309CalculateRefundResponseData() {
    }
    ReturnRefund202309CalculateRefundResponseData.getAttributeTypeMap = function () {
        return ReturnRefund202309CalculateRefundResponseData.attributeTypeMap;
    };
    ReturnRefund202309CalculateRefundResponseData.discriminator = undefined;
    ReturnRefund202309CalculateRefundResponseData.attributeTypeMap = [
        {
            "name": "orderRefundAmount",
            "baseName": "order_refund_amount",
            "type": "ReturnRefund202309CalculateRefundResponseDataOrderRefundAmount"
        }
    ];
    return ReturnRefund202309CalculateRefundResponseData;
}());
exports.ReturnRefund202309CalculateRefundResponseData = ReturnRefund202309CalculateRefundResponseData;
