"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.ReturnRefund202309CancelOrderResponseData = void 0;
var ReturnRefund202309CancelOrderResponseData = /** @class */ (function () {
    function ReturnRefund202309CancelOrderResponseData() {
    }
    ReturnRefund202309CancelOrderResponseData.getAttributeTypeMap = function () {
        return ReturnRefund202309CancelOrderResponseData.attributeTypeMap;
    };
    ReturnRefund202309CancelOrderResponseData.discriminator = undefined;
    ReturnRefund202309CancelOrderResponseData.attributeTypeMap = [
        {
            "name": "cancelId",
            "baseName": "cancel_id",
            "type": "string"
        },
        {
            "name": "cancelStatus",
            "baseName": "cancel_status",
            "type": "string"
        }
    ];
    return ReturnRefund202309CancelOrderResponseData;
}());
exports.ReturnRefund202309CancelOrderResponseData = ReturnRefund202309CancelOrderResponseData;
