"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.ReturnRefund202309CreateReturnResponse = void 0;
var ReturnRefund202309CreateReturnResponse = /** @class */ (function () {
    function ReturnRefund202309CreateReturnResponse() {
    }
    ReturnRefund202309CreateReturnResponse.getAttributeTypeMap = function () {
        return ReturnRefund202309CreateReturnResponse.attributeTypeMap;
    };
    ReturnRefund202309CreateReturnResponse.discriminator = undefined;
    ReturnRefund202309CreateReturnResponse.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "ReturnRefund202309CreateReturnResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }
    ];
    return ReturnRefund202309CreateReturnResponse;
}());
exports.ReturnRefund202309CreateReturnResponse = ReturnRefund202309CreateReturnResponse;
