"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.ReturnRefund202309CreateReturnRequestBodySkus = void 0;
var ReturnRefund202309CreateReturnRequestBodySkus = /** @class */ (function () {
    function ReturnRefund202309CreateReturnRequestBodySkus() {
    }
    ReturnRefund202309CreateReturnRequestBodySkus.getAttributeTypeMap = function () {
        return ReturnRefund202309CreateReturnRequestBodySkus.attributeTypeMap;
    };
    ReturnRefund202309CreateReturnRequestBodySkus.discriminator = undefined;
    ReturnRefund202309CreateReturnRequestBodySkus.attributeTypeMap = [
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        }
    ];
    return ReturnRefund202309CreateReturnRequestBodySkus;
}());
exports.ReturnRefund202309CreateReturnRequestBodySkus = ReturnRefund202309CreateReturnRequestBodySkus;
