"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.ReturnRefund202309CreateReturnResponseData = void 0;
var ReturnRefund202309CreateReturnResponseData = /** @class */ (function () {
    function ReturnRefund202309CreateReturnResponseData() {
    }
    ReturnRefund202309CreateReturnResponseData.getAttributeTypeMap = function () {
        return ReturnRefund202309CreateReturnResponseData.attributeTypeMap;
    };
    ReturnRefund202309CreateReturnResponseData.discriminator = undefined;
    ReturnRefund202309CreateReturnResponseData.attributeTypeMap = [
        {
            "name": "returnId",
            "baseName": "return_id",
            "type": "string"
        },
        {
            "name": "returnStatus",
            "baseName": "return_status",
            "type": "string"
        }
    ];
    return ReturnRefund202309CreateReturnResponseData;
}());
exports.ReturnRefund202309CreateReturnResponseData = ReturnRefund202309CreateReturnResponseData;
