"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.ReturnRefund202309GetAftersaleEligibilityResponseDataSkuEligibility = void 0;
var ReturnRefund202309GetAftersaleEligibilityResponseDataSkuEligibility = /** @class */ (function () {
    function ReturnRefund202309GetAftersaleEligibilityResponseDataSkuEligibility() {
    }
    ReturnRefund202309GetAftersaleEligibilityResponseDataSkuEligibility.getAttributeTypeMap = function () {
        return ReturnRefund202309GetAftersaleEligibilityResponseDataSkuEligibility.attributeTypeMap;
    };
    ReturnRefund202309GetAftersaleEligibilityResponseDataSkuEligibility.discriminator = undefined;
    ReturnRefund202309GetAftersaleEligibilityResponseDataSkuEligibility.attributeTypeMap = [
        {
            "name": "lineItemEligibility",
            "baseName": "line_item_eligibility",
            "type": "Array<ReturnRefund202309GetAftersaleEligibilityResponseDataSkuEligibilityLineItemEligibility>"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        }
    ];
    return ReturnRefund202309GetAftersaleEligibilityResponseDataSkuEligibility;
}());
exports.ReturnRefund202309GetAftersaleEligibilityResponseDataSkuEligibility = ReturnRefund202309GetAftersaleEligibilityResponseDataSkuEligibility;
