"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.ReturnRefund202309RejectCancellationRequestBodyImages = void 0;
var ReturnRefund202309RejectCancellationRequestBodyImages = /** @class */ (function () {
    function ReturnRefund202309RejectCancellationRequestBodyImages() {
    }
    ReturnRefund202309RejectCancellationRequestBodyImages.getAttributeTypeMap = function () {
        return ReturnRefund202309RejectCancellationRequestBodyImages.attributeTypeMap;
    };
    ReturnRefund202309RejectCancellationRequestBodyImages.discriminator = undefined;
    ReturnRefund202309RejectCancellationRequestBodyImages.attributeTypeMap = [
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "imageId",
            "baseName": "image_id",
            "type": "string"
        },
        {
            "name": "mimeType",
            "baseName": "mime_type",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        }
    ];
    return ReturnRefund202309RejectCancellationRequestBodyImages;
}());
exports.ReturnRefund202309RejectCancellationRequestBodyImages = ReturnRefund202309RejectCancellationRequestBodyImages;
