"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.ReturnRefund202309RejectReturnRequestBodyImages = void 0;
var ReturnRefund202309RejectReturnRequestBodyImages = /** @class */ (function () {
    function ReturnRefund202309RejectReturnRequestBodyImages() {
    }
    ReturnRefund202309RejectReturnRequestBodyImages.getAttributeTypeMap = function () {
        return ReturnRefund202309RejectReturnRequestBodyImages.attributeTypeMap;
    };
    ReturnRefund202309RejectReturnRequestBodyImages.discriminator = undefined;
    ReturnRefund202309RejectReturnRequestBodyImages.attributeTypeMap = [
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "imageId",
            "baseName": "image_id",
            "type": "string"
        },
        {
            "name": "mimeType",
            "baseName": "mime_type",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        }
    ];
    return ReturnRefund202309RejectReturnRequestBodyImages;
}());
exports.ReturnRefund202309RejectReturnRequestBodyImages = ReturnRefund202309RejectReturnRequestBodyImages;
