"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.ReturnRefund202309SearchReturnsResponseDataReturnOrdersReturnLineItemsProductImage = void 0;
var ReturnRefund202309SearchReturnsResponseDataReturnOrdersReturnLineItemsProductImage = /** @class */ (function () {
    function ReturnRefund202309SearchReturnsResponseDataReturnOrdersReturnLineItemsProductImage() {
    }
    ReturnRefund202309SearchReturnsResponseDataReturnOrdersReturnLineItemsProductImage.getAttributeTypeMap = function () {
        return ReturnRefund202309SearchReturnsResponseDataReturnOrdersReturnLineItemsProductImage.attributeTypeMap;
    };
    ReturnRefund202309SearchReturnsResponseDataReturnOrdersReturnLineItemsProductImage.discriminator = undefined;
    ReturnRefund202309SearchReturnsResponseDataReturnOrdersReturnLineItemsProductImage.attributeTypeMap = [
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        }
    ];
    return ReturnRefund202309SearchReturnsResponseDataReturnOrdersReturnLineItemsProductImage;
}());
exports.ReturnRefund202309SearchReturnsResponseDataReturnOrdersReturnLineItemsProductImage = ReturnRefund202309SearchReturnsResponseDataReturnOrdersReturnLineItemsProductImage;
