"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.ReturnRefund202309SearchCancellationsResponseData = void 0;
var ReturnRefund202309SearchCancellationsResponseData = /** @class */ (function () {
    function ReturnRefund202309SearchCancellationsResponseData() {
    }
    ReturnRefund202309SearchCancellationsResponseData.getAttributeTypeMap = function () {
        return ReturnRefund202309SearchCancellationsResponseData.attributeTypeMap;
    };
    ReturnRefund202309SearchCancellationsResponseData.discriminator = undefined;
    ReturnRefund202309SearchCancellationsResponseData.attributeTypeMap = [
        {
            "name": "cancellations",
            "baseName": "cancellations",
            "type": "Array<ReturnRefund202309SearchCancellationsResponseDataCancellations>"
        },
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }
    ];
    return ReturnRefund202309SearchCancellationsResponseData;
}());
exports.ReturnRefund202309SearchCancellationsResponseData = ReturnRefund202309SearchCancellationsResponseData;
