"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.ReturnRefund202309SearchReturnsResponseDataReturnOrdersDiscountAmount = void 0;
var ReturnRefund202309SearchReturnsResponseDataReturnOrdersDiscountAmount = /** @class */ (function () {
    function ReturnRefund202309SearchReturnsResponseDataReturnOrdersDiscountAmount() {
    }
    ReturnRefund202309SearchReturnsResponseDataReturnOrdersDiscountAmount.getAttributeTypeMap = function () {
        return ReturnRefund202309SearchReturnsResponseDataReturnOrdersDiscountAmount.attributeTypeMap;
    };
    ReturnRefund202309SearchReturnsResponseDataReturnOrdersDiscountAmount.discriminator = undefined;
    ReturnRefund202309SearchReturnsResponseDataReturnOrdersDiscountAmount.attributeTypeMap = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "productPlatformDiscount",
            "baseName": "product_platform_discount",
            "type": "string"
        },
        {
            "name": "productSellerDiscount",
            "baseName": "product_seller_discount",
            "type": "string"
        },
        {
            "name": "shippingFeePlatformDiscount",
            "baseName": "shipping_fee_platform_discount",
            "type": "string"
        },
        {
            "name": "shippingFeeSellerDiscount",
            "baseName": "shipping_fee_seller_discount",
            "type": "string"
        }
    ];
    return ReturnRefund202309SearchReturnsResponseDataReturnOrdersDiscountAmount;
}());
exports.ReturnRefund202309SearchReturnsResponseDataReturnOrdersDiscountAmount = ReturnRefund202309SearchReturnsResponseDataReturnOrdersDiscountAmount;
