"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309ActivateProductResponseData = void 0;
var Product202309ActivateProductResponseData = /** @class */ (function () {
    function Product202309ActivateProductResponseData() {
    }
    Product202309ActivateProductResponseData.getAttributeTypeMap = function () {
        return Product202309ActivateProductResponseData.attributeTypeMap;
    };
    Product202309ActivateProductResponseData.discriminator = undefined;
    Product202309ActivateProductResponseData.attributeTypeMap = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<Product202309ActivateProductResponseDataErrors>"
        }
    ];
    return Product202309ActivateProductResponseData;
}());
exports.Product202309ActivateProductResponseData = Product202309ActivateProductResponseData;
