"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309ActivateProductRequestBody = void 0;
var Product202309ActivateProductRequestBody = /** @class */ (function () {
    function Product202309ActivateProductRequestBody() {
    }
    Product202309ActivateProductRequestBody.getAttributeTypeMap = function () {
        return Product202309ActivateProductRequestBody.attributeTypeMap;
    };
    Product202309ActivateProductRequestBody.discriminator = undefined;
    Product202309ActivateProductRequestBody.attributeTypeMap = [
        {
            "name": "listingPlatforms",
            "baseName": "listing_platforms",
            "type": "Array<string>"
        },
        {
            "name": "productIds",
            "baseName": "product_ids",
            "type": "Array<string>"
        }
    ];
    return Product202309ActivateProductRequestBody;
}());
exports.Product202309ActivateProductRequestBody = Product202309ActivateProductRequestBody;
