"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309ActivateProductResponseDataErrors = void 0;
var Product202309ActivateProductResponseDataErrors = /** @class */ (function () {
    function Product202309ActivateProductResponseDataErrors() {
    }
    Product202309ActivateProductResponseDataErrors.getAttributeTypeMap = function () {
        return Product202309ActivateProductResponseDataErrors.attributeTypeMap;
    };
    Product202309ActivateProductResponseDataErrors.discriminator = undefined;
    Product202309ActivateProductResponseDataErrors.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "Product202309ActivateProductResponseDataErrorsDetail"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }
    ];
    return Product202309ActivateProductResponseDataErrors;
}());
exports.Product202309ActivateProductResponseDataErrors = Product202309ActivateProductResponseDataErrors;
