"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309CheckProductListingResponseDataDiagnoses = void 0;
var Product202309CheckProductListingResponseDataDiagnoses = /** @class */ (function () {
    function Product202309CheckProductListingResponseDataDiagnoses() {
    }
    Product202309CheckProductListingResponseDataDiagnoses.getAttributeTypeMap = function () {
        return Product202309CheckProductListingResponseDataDiagnoses.attributeTypeMap;
    };
    Product202309CheckProductListingResponseDataDiagnoses.discriminator = undefined;
    Product202309CheckProductListingResponseDataDiagnoses.attributeTypeMap = [
        {
            "name": "diagnosisResults",
            "baseName": "diagnosis_results",
            "type": "Array<Product202309CheckProductListingResponseDataDiagnosesDiagnosisResults>"
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "string"
        },
        {
            "name": "suggestions",
            "baseName": "suggestions",
            "type": "Product202309CheckProductListingResponseDataDiagnosesSuggestions"
        }
    ];
    return Product202309CheckProductListingResponseDataDiagnoses;
}());
exports.Product202309CheckProductListingResponseDataDiagnoses = Product202309CheckProductListingResponseDataDiagnoses;
