"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309CheckListingPrerequisitesResponseData = void 0;
var Product202309CheckListingPrerequisitesResponseData = /** @class */ (function () {
    function Product202309CheckListingPrerequisitesResponseData() {
    }
    Product202309CheckListingPrerequisitesResponseData.getAttributeTypeMap = function () {
        return Product202309CheckListingPrerequisitesResponseData.attributeTypeMap;
    };
    Product202309CheckListingPrerequisitesResponseData.discriminator = undefined;
    Product202309CheckListingPrerequisitesResponseData.attributeTypeMap = [
        {
            "name": "shop",
            "baseName": "shop",
            "type": "Product202309CheckListingPrerequisitesResponseDataShop"
        }
    ];
    return Product202309CheckListingPrerequisitesResponseData;
}());
exports.Product202309CheckListingPrerequisitesResponseData = Product202309CheckListingPrerequisitesResponseData;
