"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309CheckProductListingRequestBodySkusListPrice = void 0;
var Product202309CheckProductListingRequestBodySkusListPrice = /** @class */ (function () {
    function Product202309CheckProductListingRequestBodySkusListPrice() {
    }
    Product202309CheckProductListingRequestBodySkusListPrice.getAttributeTypeMap = function () {
        return Product202309CheckProductListingRequestBodySkusListPrice.attributeTypeMap;
    };
    Product202309CheckProductListingRequestBodySkusListPrice.discriminator = undefined;
    Product202309CheckProductListingRequestBodySkusListPrice.attributeTypeMap = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        }
    ];
    return Product202309CheckProductListingRequestBodySkusListPrice;
}());
exports.Product202309CheckProductListingRequestBodySkusListPrice = Product202309CheckProductListingRequestBodySkusListPrice;
