"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309CheckProductListingRequestBodyCertificationsFiles = void 0;
var Product202309CheckProductListingRequestBodyCertificationsFiles = /** @class */ (function () {
    function Product202309CheckProductListingRequestBodyCertificationsFiles() {
    }
    Product202309CheckProductListingRequestBodyCertificationsFiles.getAttributeTypeMap = function () {
        return Product202309CheckProductListingRequestBodyCertificationsFiles.attributeTypeMap;
    };
    Product202309CheckProductListingRequestBodyCertificationsFiles.discriminator = undefined;
    Product202309CheckProductListingRequestBodyCertificationsFiles.attributeTypeMap = [
        {
            "name": "format",
            "baseName": "format",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }
    ];
    return Product202309CheckProductListingRequestBodyCertificationsFiles;
}());
exports.Product202309CheckProductListingRequestBodyCertificationsFiles = Product202309CheckProductListingRequestBodyCertificationsFiles;
