"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309CheckProductListingRequestBodyProductAttributesValues = void 0;
var Product202309CheckProductListingRequestBodyProductAttributesValues = /** @class */ (function () {
    function Product202309CheckProductListingRequestBodyProductAttributesValues() {
    }
    Product202309CheckProductListingRequestBodyProductAttributesValues.getAttributeTypeMap = function () {
        return Product202309CheckProductListingRequestBodyProductAttributesValues.attributeTypeMap;
    };
    Product202309CheckProductListingRequestBodyProductAttributesValues.discriminator = undefined;
    Product202309CheckProductListingRequestBodyProductAttributesValues.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }
    ];
    return Product202309CheckProductListingRequestBodyProductAttributesValues;
}());
exports.Product202309CheckProductListingRequestBodyProductAttributesValues = Product202309CheckProductListingRequestBodyProductAttributesValues;
