"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309CheckListingPrerequisitesResponseDataShop = void 0;
var Product202309CheckListingPrerequisitesResponseDataShop = /** @class */ (function () {
    function Product202309CheckListingPrerequisitesResponseDataShop() {
    }
    Product202309CheckListingPrerequisitesResponseDataShop.getAttributeTypeMap = function () {
        return Product202309CheckListingPrerequisitesResponseDataShop.attributeTypeMap;
    };
    Product202309CheckListingPrerequisitesResponseDataShop.discriminator = undefined;
    Product202309CheckListingPrerequisitesResponseDataShop.attributeTypeMap = [
        {
            "name": "bankAccount",
            "baseName": "bank_account",
            "type": "string"
        },
        {
            "name": "contactInfo",
            "baseName": "contact_info",
            "type": "string"
        },
        {
            "name": "gne",
            "baseName": "gne",
            "type": "Product202309CheckListingPrerequisitesResponseDataShopGne"
        },
        {
            "name": "logistics",
            "baseName": "logistics",
            "type": "Product202309CheckListingPrerequisitesResponseDataShopLogistics"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "taxInfo",
            "baseName": "tax_info",
            "type": "string"
        }
    ];
    return Product202309CheckListingPrerequisitesResponseDataShop;
}());
exports.Product202309CheckListingPrerequisitesResponseDataShop = Product202309CheckListingPrerequisitesResponseDataShop;
