"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309CheckProductListingResponseDataFailReasons = void 0;
var Product202309CheckProductListingResponseDataFailReasons = /** @class */ (function () {
    function Product202309CheckProductListingResponseDataFailReasons() {
    }
    Product202309CheckProductListingResponseDataFailReasons.getAttributeTypeMap = function () {
        return Product202309CheckProductListingResponseDataFailReasons.attributeTypeMap;
    };
    Product202309CheckProductListingResponseDataFailReasons.discriminator = undefined;
    Product202309CheckProductListingResponseDataFailReasons.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }
    ];
    return Product202309CheckProductListingResponseDataFailReasons;
}());
exports.Product202309CheckProductListingResponseDataFailReasons = Product202309CheckProductListingResponseDataFailReasons;
