"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309CheckProductListingResponseDataDiagnosesDiagnosisResults = void 0;
var Product202309CheckProductListingResponseDataDiagnosesDiagnosisResults = /** @class */ (function () {
    function Product202309CheckProductListingResponseDataDiagnosesDiagnosisResults() {
    }
    Product202309CheckProductListingResponseDataDiagnosesDiagnosisResults.getAttributeTypeMap = function () {
        return Product202309CheckProductListingResponseDataDiagnosesDiagnosisResults.attributeTypeMap;
    };
    Product202309CheckProductListingResponseDataDiagnosesDiagnosisResults.discriminator = undefined;
    Product202309CheckProductListingResponseDataDiagnosesDiagnosisResults.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "howToSolve",
            "baseName": "how_to_solve",
            "type": "string"
        },
        {
            "name": "qualityTier",
            "baseName": "quality_tier",
            "type": "string"
        }
    ];
    return Product202309CheckProductListingResponseDataDiagnosesDiagnosisResults;
}());
exports.Product202309CheckProductListingResponseDataDiagnosesDiagnosisResults = Product202309CheckProductListingResponseDataDiagnosesDiagnosisResults;
