"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309CreateProductRequestBodyPackageWeight = void 0;
var Product202309CreateProductRequestBodyPackageWeight = /** @class */ (function () {
    function Product202309CreateProductRequestBodyPackageWeight() {
    }
    Product202309CreateProductRequestBodyPackageWeight.getAttributeTypeMap = function () {
        return Product202309CreateProductRequestBodyPackageWeight.attributeTypeMap;
    };
    Product202309CreateProductRequestBodyPackageWeight.discriminator = undefined;
    Product202309CreateProductRequestBodyPackageWeight.attributeTypeMap = [
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }
    ];
    return Product202309CreateProductRequestBodyPackageWeight;
}());
exports.Product202309CreateProductRequestBodyPackageWeight = Product202309CreateProductRequestBodyPackageWeight;
