"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309CreateProductRequestBodyCertificationsFiles = void 0;
var Product202309CreateProductRequestBodyCertificationsFiles = /** @class */ (function () {
    function Product202309CreateProductRequestBodyCertificationsFiles() {
    }
    Product202309CreateProductRequestBodyCertificationsFiles.getAttributeTypeMap = function () {
        return Product202309CreateProductRequestBodyCertificationsFiles.attributeTypeMap;
    };
    Product202309CreateProductRequestBodyCertificationsFiles.discriminator = undefined;
    Product202309CreateProductRequestBodyCertificationsFiles.attributeTypeMap = [
        {
            "name": "format",
            "baseName": "format",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }
    ];
    return Product202309CreateProductRequestBodyCertificationsFiles;
}());
exports.Product202309CreateProductRequestBodyCertificationsFiles = Product202309CreateProductRequestBodyCertificationsFiles;
