"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309CreateProductRequestBodyMainImages = void 0;
var Product202309CreateProductRequestBodyMainImages = /** @class */ (function () {
    function Product202309CreateProductRequestBodyMainImages() {
    }
    Product202309CreateProductRequestBodyMainImages.getAttributeTypeMap = function () {
        return Product202309CreateProductRequestBodyMainImages.attributeTypeMap;
    };
    Product202309CreateProductRequestBodyMainImages.discriminator = undefined;
    Product202309CreateProductRequestBodyMainImages.attributeTypeMap = [
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string"
        }
    ];
    return Product202309CreateProductRequestBodyMainImages;
}());
exports.Product202309CreateProductRequestBodyMainImages = Product202309CreateProductRequestBodyMainImages;
