"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309CreateProductRequestBodySkusListPrice = void 0;
var Product202309CreateProductRequestBodySkusListPrice = /** @class */ (function () {
    function Product202309CreateProductRequestBodySkusListPrice() {
    }
    Product202309CreateProductRequestBodySkusListPrice.getAttributeTypeMap = function () {
        return Product202309CreateProductRequestBodySkusListPrice.attributeTypeMap;
    };
    Product202309CreateProductRequestBodySkusListPrice.discriminator = undefined;
    Product202309CreateProductRequestBodySkusListPrice.attributeTypeMap = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        }
    ];
    return Product202309CreateProductRequestBodySkusListPrice;
}());
exports.Product202309CreateProductRequestBodySkusListPrice = Product202309CreateProductRequestBodySkusListPrice;
