"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309CreateGlobalProductRequestBodySkusIdentifierCode = void 0;
var Product202309CreateGlobalProductRequestBodySkusIdentifierCode = /** @class */ (function () {
    function Product202309CreateGlobalProductRequestBodySkusIdentifierCode() {
    }
    Product202309CreateGlobalProductRequestBodySkusIdentifierCode.getAttributeTypeMap = function () {
        return Product202309CreateGlobalProductRequestBodySkusIdentifierCode.attributeTypeMap;
    };
    Product202309CreateGlobalProductRequestBodySkusIdentifierCode.discriminator = undefined;
    Product202309CreateGlobalProductRequestBodySkusIdentifierCode.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }
    ];
    return Product202309CreateGlobalProductRequestBodySkusIdentifierCode;
}());
exports.Product202309CreateGlobalProductRequestBodySkusIdentifierCode = Product202309CreateGlobalProductRequestBodySkusIdentifierCode;
