"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309CreateProductRequestBodySkusSalesAttributesSkuImg = void 0;
var Product202309CreateProductRequestBodySkusSalesAttributesSkuImg = /** @class */ (function () {
    function Product202309CreateProductRequestBodySkusSalesAttributesSkuImg() {
    }
    Product202309CreateProductRequestBodySkusSalesAttributesSkuImg.getAttributeTypeMap = function () {
        return Product202309CreateProductRequestBodySkusSalesAttributesSkuImg.attributeTypeMap;
    };
    Product202309CreateProductRequestBodySkusSalesAttributesSkuImg.discriminator = undefined;
    Product202309CreateProductRequestBodySkusSalesAttributesSkuImg.attributeTypeMap = [
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string"
        }
    ];
    return Product202309CreateProductRequestBodySkusSalesAttributesSkuImg;
}());
exports.Product202309CreateProductRequestBodySkusSalesAttributesSkuImg = Product202309CreateProductRequestBodySkusSalesAttributesSkuImg;
