"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309CreateGlobalProductRequestBodyProductAttributes = void 0;
var Product202309CreateGlobalProductRequestBodyProductAttributes = /** @class */ (function () {
    function Product202309CreateGlobalProductRequestBodyProductAttributes() {
    }
    Product202309CreateGlobalProductRequestBodyProductAttributes.getAttributeTypeMap = function () {
        return Product202309CreateGlobalProductRequestBodyProductAttributes.attributeTypeMap;
    };
    Product202309CreateGlobalProductRequestBodyProductAttributes.discriminator = undefined;
    Product202309CreateGlobalProductRequestBodyProductAttributes.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<Product202309CreateGlobalProductRequestBodyProductAttributesValues>"
        }
    ];
    return Product202309CreateGlobalProductRequestBodyProductAttributes;
}());
exports.Product202309CreateGlobalProductRequestBodyProductAttributes = Product202309CreateGlobalProductRequestBodyProductAttributes;
