"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309CreateGlobalProductRequestBodyPackageWeight = void 0;
var Product202309CreateGlobalProductRequestBodyPackageWeight = /** @class */ (function () {
    function Product202309CreateGlobalProductRequestBodyPackageWeight() {
    }
    Product202309CreateGlobalProductRequestBodyPackageWeight.getAttributeTypeMap = function () {
        return Product202309CreateGlobalProductRequestBodyPackageWeight.attributeTypeMap;
    };
    Product202309CreateGlobalProductRequestBodyPackageWeight.discriminator = undefined;
    Product202309CreateGlobalProductRequestBodyPackageWeight.attributeTypeMap = [
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }
    ];
    return Product202309CreateGlobalProductRequestBodyPackageWeight;
}());
exports.Product202309CreateGlobalProductRequestBodyPackageWeight = Product202309CreateGlobalProductRequestBodyPackageWeight;
