"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309CreateProductRequestBodySkusPreSale = void 0;
var Product202309CreateProductRequestBodySkusPreSale = /** @class */ (function () {
    function Product202309CreateProductRequestBodySkusPreSale() {
    }
    Product202309CreateProductRequestBodySkusPreSale.getAttributeTypeMap = function () {
        return Product202309CreateProductRequestBodySkusPreSale.attributeTypeMap;
    };
    Product202309CreateProductRequestBodySkusPreSale.discriminator = undefined;
    Product202309CreateProductRequestBodySkusPreSale.attributeTypeMap = [
        {
            "name": "fulfillmentType",
            "baseName": "fulfillment_type",
            "type": "Product202309CreateProductRequestBodySkusPreSaleFulfillmentType"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }
    ];
    return Product202309CreateProductRequestBodySkusPreSale;
}());
exports.Product202309CreateProductRequestBodySkusPreSale = Product202309CreateProductRequestBodySkusPreSale;
