"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309CreateGlobalProductRequestBodyCertificationsImages = void 0;
var Product202309CreateGlobalProductRequestBodyCertificationsImages = /** @class */ (function () {
    function Product202309CreateGlobalProductRequestBodyCertificationsImages() {
    }
    Product202309CreateGlobalProductRequestBodyCertificationsImages.getAttributeTypeMap = function () {
        return Product202309CreateGlobalProductRequestBodyCertificationsImages.attributeTypeMap;
    };
    Product202309CreateGlobalProductRequestBodyCertificationsImages.discriminator = undefined;
    Product202309CreateGlobalProductRequestBodyCertificationsImages.attributeTypeMap = [
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string"
        }
    ];
    return Product202309CreateGlobalProductRequestBodyCertificationsImages;
}());
exports.Product202309CreateGlobalProductRequestBodyCertificationsImages = Product202309CreateGlobalProductRequestBodyCertificationsImages;
