"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309CreateProductRequestBodySkusSalesAttributesSupplementarySkuImages = void 0;
var Product202309CreateProductRequestBodySkusSalesAttributesSupplementarySkuImages = /** @class */ (function () {
    function Product202309CreateProductRequestBodySkusSalesAttributesSupplementarySkuImages() {
    }
    Product202309CreateProductRequestBodySkusSalesAttributesSupplementarySkuImages.getAttributeTypeMap = function () {
        return Product202309CreateProductRequestBodySkusSalesAttributesSupplementarySkuImages.attributeTypeMap;
    };
    Product202309CreateProductRequestBodySkusSalesAttributesSupplementarySkuImages.discriminator = undefined;
    Product202309CreateProductRequestBodySkusSalesAttributesSupplementarySkuImages.attributeTypeMap = [
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string"
        }
    ];
    return Product202309CreateProductRequestBodySkusSalesAttributesSupplementarySkuImages;
}());
exports.Product202309CreateProductRequestBodySkusSalesAttributesSupplementarySkuImages = Product202309CreateProductRequestBodySkusSalesAttributesSupplementarySkuImages;
