"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309DeleteProductsResponseData = void 0;
var Product202309DeleteProductsResponseData = /** @class */ (function () {
    function Product202309DeleteProductsResponseData() {
    }
    Product202309DeleteProductsResponseData.getAttributeTypeMap = function () {
        return Product202309DeleteProductsResponseData.attributeTypeMap;
    };
    Product202309DeleteProductsResponseData.discriminator = undefined;
    Product202309DeleteProductsResponseData.attributeTypeMap = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<Product202309DeleteProductsResponseDataErrors>"
        }
    ];
    return Product202309DeleteProductsResponseData;
}());
exports.Product202309DeleteProductsResponseData = Product202309DeleteProductsResponseData;
