"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309DeleteGlobalProductsRequestBody = void 0;
var Product202309DeleteGlobalProductsRequestBody = /** @class */ (function () {
    function Product202309DeleteGlobalProductsRequestBody() {
    }
    Product202309DeleteGlobalProductsRequestBody.getAttributeTypeMap = function () {
        return Product202309DeleteGlobalProductsRequestBody.attributeTypeMap;
    };
    Product202309DeleteGlobalProductsRequestBody.discriminator = undefined;
    Product202309DeleteGlobalProductsRequestBody.attributeTypeMap = [
        {
            "name": "globalProductIds",
            "baseName": "global_product_ids",
            "type": "Array<string>"
        }
    ];
    return Product202309DeleteGlobalProductsRequestBody;
}());
exports.Product202309DeleteGlobalProductsRequestBody = Product202309DeleteGlobalProductsRequestBody;
