"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309DeleteGlobalProductsResponseDataErrorsDetail = void 0;
var Product202309DeleteGlobalProductsResponseDataErrorsDetail = /** @class */ (function () {
    function Product202309DeleteGlobalProductsResponseDataErrorsDetail() {
    }
    Product202309DeleteGlobalProductsResponseDataErrorsDetail.getAttributeTypeMap = function () {
        return Product202309DeleteGlobalProductsResponseDataErrorsDetail.attributeTypeMap;
    };
    Product202309DeleteGlobalProductsResponseDataErrorsDetail.discriminator = undefined;
    Product202309DeleteGlobalProductsResponseDataErrorsDetail.attributeTypeMap = [
        {
            "name": "globalProductId",
            "baseName": "global_product_id",
            "type": "string"
        }
    ];
    return Product202309DeleteGlobalProductsResponseDataErrorsDetail;
}());
exports.Product202309DeleteGlobalProductsResponseDataErrorsDetail = Product202309DeleteGlobalProductsResponseDataErrorsDetail;
