"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309DeleteGlobalProductsResponse = void 0;
var Product202309DeleteGlobalProductsResponse = /** @class */ (function () {
    function Product202309DeleteGlobalProductsResponse() {
    }
    Product202309DeleteGlobalProductsResponse.getAttributeTypeMap = function () {
        return Product202309DeleteGlobalProductsResponse.attributeTypeMap;
    };
    Product202309DeleteGlobalProductsResponse.discriminator = undefined;
    Product202309DeleteGlobalProductsResponse.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Product202309DeleteGlobalProductsResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }
    ];
    return Product202309DeleteGlobalProductsResponse;
}());
exports.Product202309DeleteGlobalProductsResponse = Product202309DeleteGlobalProductsResponse;
