"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309EditGlobalProductRequestBodyCertifications = void 0;
var Product202309EditGlobalProductRequestBodyCertifications = /** @class */ (function () {
    function Product202309EditGlobalProductRequestBodyCertifications() {
    }
    Product202309EditGlobalProductRequestBodyCertifications.getAttributeTypeMap = function () {
        return Product202309EditGlobalProductRequestBodyCertifications.attributeTypeMap;
    };
    Product202309EditGlobalProductRequestBodyCertifications.discriminator = undefined;
    Product202309EditGlobalProductRequestBodyCertifications.attributeTypeMap = [
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<Product202309EditGlobalProductRequestBodyCertificationsFiles>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<Product202309EditGlobalProductRequestBodyCertificationsImages>"
        }
    ];
    return Product202309EditGlobalProductRequestBodyCertifications;
}());
exports.Product202309EditGlobalProductRequestBodyCertifications = Product202309EditGlobalProductRequestBodyCertifications;
