"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309EditProductResponseDataSkus = void 0;
var Product202309EditProductResponseDataSkus = /** @class */ (function () {
    function Product202309EditProductResponseDataSkus() {
    }
    Product202309EditProductResponseDataSkus.getAttributeTypeMap = function () {
        return Product202309EditProductResponseDataSkus.attributeTypeMap;
    };
    Product202309EditProductResponseDataSkus.discriminator = undefined;
    Product202309EditProductResponseDataSkus.attributeTypeMap = [
        {
            "name": "externalSkuId",
            "baseName": "external_sku_id",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "salesAttributes",
            "baseName": "sales_attributes",
            "type": "Array<Product202309EditProductResponseDataSkusSalesAttributes>"
        },
        {
            "name": "sellerSku",
            "baseName": "seller_sku",
            "type": "string"
        }
    ];
    return Product202309EditProductResponseDataSkus;
}());
exports.Product202309EditProductResponseDataSkus = Product202309EditProductResponseDataSkus;
