"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309EditProductRequestBodySkusPrice = void 0;
var Product202309EditProductRequestBodySkusPrice = /** @class */ (function () {
    function Product202309EditProductRequestBodySkusPrice() {
    }
    Product202309EditProductRequestBodySkusPrice.getAttributeTypeMap = function () {
        return Product202309EditProductRequestBodySkusPrice.attributeTypeMap;
    };
    Product202309EditProductRequestBodySkusPrice.discriminator = undefined;
    Product202309EditProductRequestBodySkusPrice.attributeTypeMap = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "salePrice",
            "baseName": "sale_price",
            "type": "string"
        }
    ];
    return Product202309EditProductRequestBodySkusPrice;
}());
exports.Product202309EditProductRequestBodySkusPrice = Product202309EditProductRequestBodySkusPrice;
