"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309EditProductResponseDataAudit = void 0;
var Product202309EditProductResponseDataAudit = /** @class */ (function () {
    function Product202309EditProductResponseDataAudit() {
    }
    Product202309EditProductResponseDataAudit.getAttributeTypeMap = function () {
        return Product202309EditProductResponseDataAudit.attributeTypeMap;
    };
    Product202309EditProductResponseDataAudit.discriminator = undefined;
    Product202309EditProductResponseDataAudit.attributeTypeMap = [
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        }
    ];
    return Product202309EditProductResponseDataAudit;
}());
exports.Product202309EditProductResponseDataAudit = Product202309EditProductResponseDataAudit;
