"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309EditProductRequestBodyPackageDimensions = void 0;
var Product202309EditProductRequestBodyPackageDimensions = /** @class */ (function () {
    function Product202309EditProductRequestBodyPackageDimensions() {
    }
    Product202309EditProductRequestBodyPackageDimensions.getAttributeTypeMap = function () {
        return Product202309EditProductRequestBodyPackageDimensions.attributeTypeMap;
    };
    Product202309EditProductRequestBodyPackageDimensions.discriminator = undefined;
    Product202309EditProductRequestBodyPackageDimensions.attributeTypeMap = [
        {
            "name": "height",
            "baseName": "height",
            "type": "string"
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "string"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "string"
        }
    ];
    return Product202309EditProductRequestBodyPackageDimensions;
}());
exports.Product202309EditProductRequestBodyPackageDimensions = Product202309EditProductRequestBodyPackageDimensions;
