"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309EditGlobalProductRequestBodySkusSalesAttributes = void 0;
var Product202309EditGlobalProductRequestBodySkusSalesAttributes = /** @class */ (function () {
    function Product202309EditGlobalProductRequestBodySkusSalesAttributes() {
    }
    Product202309EditGlobalProductRequestBodySkusSalesAttributes.getAttributeTypeMap = function () {
        return Product202309EditGlobalProductRequestBodySkusSalesAttributes.attributeTypeMap;
    };
    Product202309EditGlobalProductRequestBodySkusSalesAttributes.discriminator = undefined;
    Product202309EditGlobalProductRequestBodySkusSalesAttributes.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "skuImg",
            "baseName": "sku_img",
            "type": "Product202309EditGlobalProductRequestBodySkusSalesAttributesSkuImg"
        },
        {
            "name": "valueId",
            "baseName": "value_id",
            "type": "string"
        },
        {
            "name": "valueName",
            "baseName": "value_name",
            "type": "string"
        }
    ];
    return Product202309EditGlobalProductRequestBodySkusSalesAttributes;
}());
exports.Product202309EditGlobalProductRequestBodySkusSalesAttributes = Product202309EditGlobalProductRequestBodySkusSalesAttributes;
