"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309EditGlobalProductRequestBodyVideo = void 0;
var Product202309EditGlobalProductRequestBodyVideo = /** @class */ (function () {
    function Product202309EditGlobalProductRequestBodyVideo() {
    }
    Product202309EditGlobalProductRequestBodyVideo.getAttributeTypeMap = function () {
        return Product202309EditGlobalProductRequestBodyVideo.attributeTypeMap;
    };
    Product202309EditGlobalProductRequestBodyVideo.discriminator = undefined;
    Product202309EditGlobalProductRequestBodyVideo.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }
    ];
    return Product202309EditGlobalProductRequestBodyVideo;
}());
exports.Product202309EditGlobalProductRequestBodyVideo = Product202309EditGlobalProductRequestBodyVideo;
