"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309EditProductRequestBodySkusCombinedSkus = void 0;
var Product202309EditProductRequestBodySkusCombinedSkus = /** @class */ (function () {
    function Product202309EditProductRequestBodySkusCombinedSkus() {
    }
    Product202309EditProductRequestBodySkusCombinedSkus.getAttributeTypeMap = function () {
        return Product202309EditProductRequestBodySkusCombinedSkus.attributeTypeMap;
    };
    Product202309EditProductRequestBodySkusCombinedSkus.discriminator = undefined;
    Product202309EditProductRequestBodySkusCombinedSkus.attributeTypeMap = [
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        },
        {
            "name": "skuCount",
            "baseName": "sku_count",
            "type": "number"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        }
    ];
    return Product202309EditProductRequestBodySkusCombinedSkus;
}());
exports.Product202309EditProductRequestBodySkusCombinedSkus = Product202309EditProductRequestBodySkusCombinedSkus;
