"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309EditGlobalProductResponseData = void 0;
var Product202309EditGlobalProductResponseData = /** @class */ (function () {
    function Product202309EditGlobalProductResponseData() {
    }
    Product202309EditGlobalProductResponseData.getAttributeTypeMap = function () {
        return Product202309EditGlobalProductResponseData.attributeTypeMap;
    };
    Product202309EditGlobalProductResponseData.discriminator = undefined;
    Product202309EditGlobalProductResponseData.attributeTypeMap = [
        {
            "name": "globalSkus",
            "baseName": "global_skus",
            "type": "Array<Product202309EditGlobalProductResponseDataGlobalSkus>"
        },
        {
            "name": "publishResults",
            "baseName": "publish_results",
            "type": "Array<Product202309EditGlobalProductResponseDataPublishResults>"
        }
    ];
    return Product202309EditGlobalProductResponseData;
}());
exports.Product202309EditGlobalProductResponseData = Product202309EditGlobalProductResponseData;
