"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309EditGlobalProductRequestBodySkusInventory = void 0;
var Product202309EditGlobalProductRequestBodySkusInventory = /** @class */ (function () {
    function Product202309EditGlobalProductRequestBodySkusInventory() {
    }
    Product202309EditGlobalProductRequestBodySkusInventory.getAttributeTypeMap = function () {
        return Product202309EditGlobalProductRequestBodySkusInventory.attributeTypeMap;
    };
    Product202309EditGlobalProductRequestBodySkusInventory.discriminator = undefined;
    Product202309EditGlobalProductRequestBodySkusInventory.attributeTypeMap = [
        {
            "name": "globalWarehouseId",
            "baseName": "global_warehouse_id",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        }
    ];
    return Product202309EditGlobalProductRequestBodySkusInventory;
}());
exports.Product202309EditGlobalProductRequestBodySkusInventory = Product202309EditGlobalProductRequestBodySkusInventory;
