"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309EditGlobalProductRequestBodyMainImages = void 0;
var Product202309EditGlobalProductRequestBodyMainImages = /** @class */ (function () {
    function Product202309EditGlobalProductRequestBodyMainImages() {
    }
    Product202309EditGlobalProductRequestBodyMainImages.getAttributeTypeMap = function () {
        return Product202309EditGlobalProductRequestBodyMainImages.attributeTypeMap;
    };
    Product202309EditGlobalProductRequestBodyMainImages.discriminator = undefined;
    Product202309EditGlobalProductRequestBodyMainImages.attributeTypeMap = [
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string"
        }
    ];
    return Product202309EditGlobalProductRequestBodyMainImages;
}());
exports.Product202309EditGlobalProductRequestBodyMainImages = Product202309EditGlobalProductRequestBodyMainImages;
