"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309EditGlobalProductRequestBodySizeChart = void 0;
var Product202309EditGlobalProductRequestBodySizeChart = /** @class */ (function () {
    function Product202309EditGlobalProductRequestBodySizeChart() {
    }
    Product202309EditGlobalProductRequestBodySizeChart.getAttributeTypeMap = function () {
        return Product202309EditGlobalProductRequestBodySizeChart.attributeTypeMap;
    };
    Product202309EditGlobalProductRequestBodySizeChart.discriminator = undefined;
    Product202309EditGlobalProductRequestBodySizeChart.attributeTypeMap = [
        {
            "name": "image",
            "baseName": "image",
            "type": "Product202309EditGlobalProductRequestBodySizeChartImage"
        },
        {
            "name": "template",
            "baseName": "template",
            "type": "Product202309EditGlobalProductRequestBodySizeChartTemplate"
        }
    ];
    return Product202309EditGlobalProductRequestBodySizeChart;
}());
exports.Product202309EditGlobalProductRequestBodySizeChart = Product202309EditGlobalProductRequestBodySizeChart;
