"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309EditProductRequestBodySkusPreSale = void 0;
var Product202309EditProductRequestBodySkusPreSale = /** @class */ (function () {
    function Product202309EditProductRequestBodySkusPreSale() {
    }
    Product202309EditProductRequestBodySkusPreSale.getAttributeTypeMap = function () {
        return Product202309EditProductRequestBodySkusPreSale.attributeTypeMap;
    };
    Product202309EditProductRequestBodySkusPreSale.discriminator = undefined;
    Product202309EditProductRequestBodySkusPreSale.attributeTypeMap = [
        {
            "name": "fulfillmentType",
            "baseName": "fulfillment_type",
            "type": "Product202309EditProductRequestBodySkusPreSaleFulfillmentType"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }
    ];
    return Product202309EditProductRequestBodySkusPreSale;
}());
exports.Product202309EditProductRequestBodySkusPreSale = Product202309EditProductRequestBodySkusPreSale;
