"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309EditGlobalProductRequestBodySkusSalePrices = void 0;
var Product202309EditGlobalProductRequestBodySkusSalePrices = /** @class */ (function () {
    function Product202309EditGlobalProductRequestBodySkusSalePrices() {
    }
    Product202309EditGlobalProductRequestBodySkusSalePrices.getAttributeTypeMap = function () {
        return Product202309EditGlobalProductRequestBodySkusSalePrices.attributeTypeMap;
    };
    Product202309EditGlobalProductRequestBodySkusSalePrices.discriminator = undefined;
    Product202309EditGlobalProductRequestBodySkusSalePrices.attributeTypeMap = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        }
    ];
    return Product202309EditGlobalProductRequestBodySkusSalePrices;
}());
exports.Product202309EditGlobalProductRequestBodySkusSalePrices = Product202309EditGlobalProductRequestBodySkusSalePrices;
