"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309EditProductRequestBodySizeChart = void 0;
var Product202309EditProductRequestBodySizeChart = /** @class */ (function () {
    function Product202309EditProductRequestBodySizeChart() {
    }
    Product202309EditProductRequestBodySizeChart.getAttributeTypeMap = function () {
        return Product202309EditProductRequestBodySizeChart.attributeTypeMap;
    };
    Product202309EditProductRequestBodySizeChart.discriminator = undefined;
    Product202309EditProductRequestBodySizeChart.attributeTypeMap = [
        {
            "name": "image",
            "baseName": "image",
            "type": "Product202309EditProductRequestBodySizeChartImage"
        },
        {
            "name": "template",
            "baseName": "template",
            "type": "Product202309EditProductRequestBodySizeChartTemplate"
        }
    ];
    return Product202309EditProductRequestBodySizeChart;
}());
exports.Product202309EditProductRequestBodySizeChart = Product202309EditProductRequestBodySizeChart;
