"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309EditGlobalProductResponseDataPublishResults = void 0;
var Product202309EditGlobalProductResponseDataPublishResults = /** @class */ (function () {
    function Product202309EditGlobalProductResponseDataPublishResults() {
    }
    Product202309EditGlobalProductResponseDataPublishResults.getAttributeTypeMap = function () {
        return Product202309EditGlobalProductResponseDataPublishResults.attributeTypeMap;
    };
    Product202309EditGlobalProductResponseDataPublishResults.discriminator = undefined;
    Product202309EditGlobalProductResponseDataPublishResults.attributeTypeMap = [
        {
            "name": "failReasons",
            "baseName": "fail_reasons",
            "type": "Array<Product202309EditGlobalProductResponseDataPublishResultsFailReasons>"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        }
    ];
    return Product202309EditGlobalProductResponseDataPublishResults;
}());
exports.Product202309EditGlobalProductResponseDataPublishResults = Product202309EditGlobalProductResponseDataPublishResults;
