"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309EditGlobalProductRequestBodySkusIdentifierCode = void 0;
var Product202309EditGlobalProductRequestBodySkusIdentifierCode = /** @class */ (function () {
    function Product202309EditGlobalProductRequestBodySkusIdentifierCode() {
    }
    Product202309EditGlobalProductRequestBodySkusIdentifierCode.getAttributeTypeMap = function () {
        return Product202309EditGlobalProductRequestBodySkusIdentifierCode.attributeTypeMap;
    };
    Product202309EditGlobalProductRequestBodySkusIdentifierCode.discriminator = undefined;
    Product202309EditGlobalProductRequestBodySkusIdentifierCode.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }
    ];
    return Product202309EditGlobalProductRequestBodySkusIdentifierCode;
}());
exports.Product202309EditGlobalProductRequestBodySkusIdentifierCode = Product202309EditGlobalProductRequestBodySkusIdentifierCode;
