"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309EditProductResponseDataWarnings = void 0;
var Product202309EditProductResponseDataWarnings = /** @class */ (function () {
    function Product202309EditProductResponseDataWarnings() {
    }
    Product202309EditProductResponseDataWarnings.getAttributeTypeMap = function () {
        return Product202309EditProductResponseDataWarnings.attributeTypeMap;
    };
    Product202309EditProductResponseDataWarnings.discriminator = undefined;
    Product202309EditProductResponseDataWarnings.attributeTypeMap = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }
    ];
    return Product202309EditProductResponseDataWarnings;
}());
exports.Product202309EditProductResponseDataWarnings = Product202309EditProductResponseDataWarnings;
