"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetAttributesResponseData = void 0;
var Product202309GetAttributesResponseData = /** @class */ (function () {
    function Product202309GetAttributesResponseData() {
    }
    Product202309GetAttributesResponseData.getAttributeTypeMap = function () {
        return Product202309GetAttributesResponseData.attributeTypeMap;
    };
    Product202309GetAttributesResponseData.discriminator = undefined;
    Product202309GetAttributesResponseData.attributeTypeMap = [
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "Array<Product202309GetAttributesResponseDataAttributes>"
        }
    ];
    return Product202309GetAttributesResponseData;
}());
exports.Product202309GetAttributesResponseData = Product202309GetAttributesResponseData;
