"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetAttributesResponseDataAttributesValues = void 0;
var Product202309GetAttributesResponseDataAttributesValues = /** @class */ (function () {
    function Product202309GetAttributesResponseDataAttributesValues() {
    }
    Product202309GetAttributesResponseDataAttributesValues.getAttributeTypeMap = function () {
        return Product202309GetAttributesResponseDataAttributesValues.attributeTypeMap;
    };
    Product202309GetAttributesResponseDataAttributesValues.discriminator = undefined;
    Product202309GetAttributesResponseDataAttributesValues.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }
    ];
    return Product202309GetAttributesResponseDataAttributesValues;
}());
exports.Product202309GetAttributesResponseDataAttributesValues = Product202309GetAttributesResponseDataAttributesValues;
