"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetCategoryRulesResponseDataResponsiblePerson = void 0;
var Product202309GetCategoryRulesResponseDataResponsiblePerson = /** @class */ (function () {
    function Product202309GetCategoryRulesResponseDataResponsiblePerson() {
    }
    Product202309GetCategoryRulesResponseDataResponsiblePerson.getAttributeTypeMap = function () {
        return Product202309GetCategoryRulesResponseDataResponsiblePerson.attributeTypeMap;
    };
    Product202309GetCategoryRulesResponseDataResponsiblePerson.discriminator = undefined;
    Product202309GetCategoryRulesResponseDataResponsiblePerson.attributeTypeMap = [
        {
            "name": "isRequired",
            "baseName": "is_required",
            "type": "boolean"
        }
    ];
    return Product202309GetCategoryRulesResponseDataResponsiblePerson;
}());
exports.Product202309GetCategoryRulesResponseDataResponsiblePerson = Product202309GetCategoryRulesResponseDataResponsiblePerson;
