"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetGlobalAttributesResponseDataAttributesValues = void 0;
var Product202309GetGlobalAttributesResponseDataAttributesValues = /** @class */ (function () {
    function Product202309GetGlobalAttributesResponseDataAttributesValues() {
    }
    Product202309GetGlobalAttributesResponseDataAttributesValues.getAttributeTypeMap = function () {
        return Product202309GetGlobalAttributesResponseDataAttributesValues.attributeTypeMap;
    };
    Product202309GetGlobalAttributesResponseDataAttributesValues.discriminator = undefined;
    Product202309GetGlobalAttributesResponseDataAttributesValues.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }
    ];
    return Product202309GetGlobalAttributesResponseDataAttributesValues;
}());
exports.Product202309GetGlobalAttributesResponseDataAttributesValues = Product202309GetGlobalAttributesResponseDataAttributesValues;
