"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetGlobalProductResponseDataProductAttributes = void 0;
var Product202309GetGlobalProductResponseDataProductAttributes = /** @class */ (function () {
    function Product202309GetGlobalProductResponseDataProductAttributes() {
    }
    Product202309GetGlobalProductResponseDataProductAttributes.getAttributeTypeMap = function () {
        return Product202309GetGlobalProductResponseDataProductAttributes.attributeTypeMap;
    };
    Product202309GetGlobalProductResponseDataProductAttributes.discriminator = undefined;
    Product202309GetGlobalProductResponseDataProductAttributes.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<Product202309GetGlobalProductResponseDataProductAttributesValues>"
        }
    ];
    return Product202309GetGlobalProductResponseDataProductAttributes;
}());
exports.Product202309GetGlobalProductResponseDataProductAttributes = Product202309GetGlobalProductResponseDataProductAttributes;
