"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetGlobalProductResponseDataCategory = void 0;
var Product202309GetGlobalProductResponseDataCategory = /** @class */ (function () {
    function Product202309GetGlobalProductResponseDataCategory() {
    }
    Product202309GetGlobalProductResponseDataCategory.getAttributeTypeMap = function () {
        return Product202309GetGlobalProductResponseDataCategory.attributeTypeMap;
    };
    Product202309GetGlobalProductResponseDataCategory.discriminator = undefined;
    Product202309GetGlobalProductResponseDataCategory.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }
    ];
    return Product202309GetGlobalProductResponseDataCategory;
}());
exports.Product202309GetGlobalProductResponseDataCategory = Product202309GetGlobalProductResponseDataCategory;
