"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetGlobalCategoryRulesResponseDataResponsiblePerson = void 0;
var Product202309GetGlobalCategoryRulesResponseDataResponsiblePerson = /** @class */ (function () {
    function Product202309GetGlobalCategoryRulesResponseDataResponsiblePerson() {
    }
    Product202309GetGlobalCategoryRulesResponseDataResponsiblePerson.getAttributeTypeMap = function () {
        return Product202309GetGlobalCategoryRulesResponseDataResponsiblePerson.attributeTypeMap;
    };
    Product202309GetGlobalCategoryRulesResponseDataResponsiblePerson.discriminator = undefined;
    Product202309GetGlobalCategoryRulesResponseDataResponsiblePerson.attributeTypeMap = [
        {
            "name": "isRequired",
            "baseName": "is_required",
            "type": "boolean"
        },
        {
            "name": "optionalRegions",
            "baseName": "optional_regions",
            "type": "Array<string>"
        },
        {
            "name": "requiredRegions",
            "baseName": "required_regions",
            "type": "Array<string>"
        }
    ];
    return Product202309GetGlobalCategoryRulesResponseDataResponsiblePerson;
}());
exports.Product202309GetGlobalCategoryRulesResponseDataResponsiblePerson = Product202309GetGlobalCategoryRulesResponseDataResponsiblePerson;
