"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetGlobalProductResponseDataSizeChartImage = void 0;
var Product202309GetGlobalProductResponseDataSizeChartImage = /** @class */ (function () {
    function Product202309GetGlobalProductResponseDataSizeChartImage() {
    }
    Product202309GetGlobalProductResponseDataSizeChartImage.getAttributeTypeMap = function () {
        return Product202309GetGlobalProductResponseDataSizeChartImage.attributeTypeMap;
    };
    Product202309GetGlobalProductResponseDataSizeChartImage.discriminator = undefined;
    Product202309GetGlobalProductResponseDataSizeChartImage.attributeTypeMap = [
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        }
    ];
    return Product202309GetGlobalProductResponseDataSizeChartImage;
}());
exports.Product202309GetGlobalProductResponseDataSizeChartImage = Product202309GetGlobalProductResponseDataSizeChartImage;
