"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetProductResponseDataGlobalProductAssociationSkuMappingsSalesAttributeMappings = void 0;
var Product202309GetProductResponseDataGlobalProductAssociationSkuMappingsSalesAttributeMappings = /** @class */ (function () {
    function Product202309GetProductResponseDataGlobalProductAssociationSkuMappingsSalesAttributeMappings() {
    }
    Product202309GetProductResponseDataGlobalProductAssociationSkuMappingsSalesAttributeMappings.getAttributeTypeMap = function () {
        return Product202309GetProductResponseDataGlobalProductAssociationSkuMappingsSalesAttributeMappings.attributeTypeMap;
    };
    Product202309GetProductResponseDataGlobalProductAssociationSkuMappingsSalesAttributeMappings.discriminator = undefined;
    Product202309GetProductResponseDataGlobalProductAssociationSkuMappingsSalesAttributeMappings.attributeTypeMap = [
        {
            "name": "globalAttributeId",
            "baseName": "global_attribute_id",
            "type": "string"
        },
        {
            "name": "globalValueId",
            "baseName": "global_value_id",
            "type": "string"
        },
        {
            "name": "localAttributeId",
            "baseName": "local_attribute_id",
            "type": "string"
        },
        {
            "name": "localValueId",
            "baseName": "local_value_id",
            "type": "string"
        }
    ];
    return Product202309GetProductResponseDataGlobalProductAssociationSkuMappingsSalesAttributeMappings;
}());
exports.Product202309GetProductResponseDataGlobalProductAssociationSkuMappingsSalesAttributeMappings = Product202309GetProductResponseDataGlobalProductAssociationSkuMappingsSalesAttributeMappings;
