"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetProductResponseDataProductAttributes = void 0;
var Product202309GetProductResponseDataProductAttributes = /** @class */ (function () {
    function Product202309GetProductResponseDataProductAttributes() {
    }
    Product202309GetProductResponseDataProductAttributes.getAttributeTypeMap = function () {
        return Product202309GetProductResponseDataProductAttributes.attributeTypeMap;
    };
    Product202309GetProductResponseDataProductAttributes.discriminator = undefined;
    Product202309GetProductResponseDataProductAttributes.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<Product202309GetProductResponseDataProductAttributesValues>"
        }
    ];
    return Product202309GetProductResponseDataProductAttributes;
}());
exports.Product202309GetProductResponseDataProductAttributes = Product202309GetProductResponseDataProductAttributes;
