"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetProductResponseDataDeliveryOptions = void 0;
var Product202309GetProductResponseDataDeliveryOptions = /** @class */ (function () {
    function Product202309GetProductResponseDataDeliveryOptions() {
    }
    Product202309GetProductResponseDataDeliveryOptions.getAttributeTypeMap = function () {
        return Product202309GetProductResponseDataDeliveryOptions.attributeTypeMap;
    };
    Product202309GetProductResponseDataDeliveryOptions.discriminator = undefined;
    Product202309GetProductResponseDataDeliveryOptions.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "isAvailable",
            "baseName": "is_available",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }
    ];
    return Product202309GetProductResponseDataDeliveryOptions;
}());
exports.Product202309GetProductResponseDataDeliveryOptions = Product202309GetProductResponseDataDeliveryOptions;
