"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetProductResponseDataSizeChartTemplate = void 0;
var Product202309GetProductResponseDataSizeChartTemplate = /** @class */ (function () {
    function Product202309GetProductResponseDataSizeChartTemplate() {
    }
    Product202309GetProductResponseDataSizeChartTemplate.getAttributeTypeMap = function () {
        return Product202309GetProductResponseDataSizeChartTemplate.attributeTypeMap;
    };
    Product202309GetProductResponseDataSizeChartTemplate.discriminator = undefined;
    Product202309GetProductResponseDataSizeChartTemplate.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }
    ];
    return Product202309GetProductResponseDataSizeChartTemplate;
}());
exports.Product202309GetProductResponseDataSizeChartTemplate = Product202309GetProductResponseDataSizeChartTemplate;
