"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetProductResponseDataSizeChart = void 0;
var Product202309GetProductResponseDataSizeChart = /** @class */ (function () {
    function Product202309GetProductResponseDataSizeChart() {
    }
    Product202309GetProductResponseDataSizeChart.getAttributeTypeMap = function () {
        return Product202309GetProductResponseDataSizeChart.attributeTypeMap;
    };
    Product202309GetProductResponseDataSizeChart.discriminator = undefined;
    Product202309GetProductResponseDataSizeChart.attributeTypeMap = [
        {
            "name": "image",
            "baseName": "image",
            "type": "Product202309GetProductResponseDataSizeChartImage"
        },
        {
            "name": "template",
            "baseName": "template",
            "type": "Product202309GetProductResponseDataSizeChartTemplate"
        }
    ];
    return Product202309GetProductResponseDataSizeChart;
}());
exports.Product202309GetProductResponseDataSizeChart = Product202309GetProductResponseDataSizeChart;
