"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetProductResponseDataSkusGlobalListingPolicyReplicateSource = void 0;
var Product202309GetProductResponseDataSkusGlobalListingPolicyReplicateSource = /** @class */ (function () {
    function Product202309GetProductResponseDataSkusGlobalListingPolicyReplicateSource() {
    }
    Product202309GetProductResponseDataSkusGlobalListingPolicyReplicateSource.getAttributeTypeMap = function () {
        return Product202309GetProductResponseDataSkusGlobalListingPolicyReplicateSource.attributeTypeMap;
    };
    Product202309GetProductResponseDataSkusGlobalListingPolicyReplicateSource.discriminator = undefined;
    Product202309GetProductResponseDataSkusGlobalListingPolicyReplicateSource.attributeTypeMap = [
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        },
        {
            "name": "shopId",
            "baseName": "shop_id",
            "type": "string"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        }
    ];
    return Product202309GetProductResponseDataSkusGlobalListingPolicyReplicateSource;
}());
exports.Product202309GetProductResponseDataSkusGlobalListingPolicyReplicateSource = Product202309GetProductResponseDataSkusGlobalListingPolicyReplicateSource;
