"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetProductResponseDataBrand = void 0;
var Product202309GetProductResponseDataBrand = /** @class */ (function () {
    function Product202309GetProductResponseDataBrand() {
    }
    Product202309GetProductResponseDataBrand.getAttributeTypeMap = function () {
        return Product202309GetProductResponseDataBrand.attributeTypeMap;
    };
    Product202309GetProductResponseDataBrand.discriminator = undefined;
    Product202309GetProductResponseDataBrand.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }
    ];
    return Product202309GetProductResponseDataBrand;
}());
exports.Product202309GetProductResponseDataBrand = Product202309GetProductResponseDataBrand;
