"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetProductResponseDataPrescriptionRequirement = void 0;
var Product202309GetProductResponseDataPrescriptionRequirement = /** @class */ (function () {
    function Product202309GetProductResponseDataPrescriptionRequirement() {
    }
    Product202309GetProductResponseDataPrescriptionRequirement.getAttributeTypeMap = function () {
        return Product202309GetProductResponseDataPrescriptionRequirement.attributeTypeMap;
    };
    Product202309GetProductResponseDataPrescriptionRequirement.discriminator = undefined;
    Product202309GetProductResponseDataPrescriptionRequirement.attributeTypeMap = [
        {
            "name": "needsPrescription",
            "baseName": "needs_prescription",
            "type": "boolean"
        }
    ];
    return Product202309GetProductResponseDataPrescriptionRequirement;
}());
exports.Product202309GetProductResponseDataPrescriptionRequirement = Product202309GetProductResponseDataPrescriptionRequirement;
