"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetProductResponseDataGlobalProductAssociation = void 0;
var Product202309GetProductResponseDataGlobalProductAssociation = /** @class */ (function () {
    function Product202309GetProductResponseDataGlobalProductAssociation() {
    }
    Product202309GetProductResponseDataGlobalProductAssociation.getAttributeTypeMap = function () {
        return Product202309GetProductResponseDataGlobalProductAssociation.attributeTypeMap;
    };
    Product202309GetProductResponseDataGlobalProductAssociation.discriminator = undefined;
    Product202309GetProductResponseDataGlobalProductAssociation.attributeTypeMap = [
        {
            "name": "globalProductId",
            "baseName": "global_product_id",
            "type": "string"
        },
        {
            "name": "skuMappings",
            "baseName": "sku_mappings",
            "type": "Array<Product202309GetProductResponseDataGlobalProductAssociationSkuMappings>"
        }
    ];
    return Product202309GetProductResponseDataGlobalProductAssociation;
}());
exports.Product202309GetProductResponseDataGlobalProductAssociation = Product202309GetProductResponseDataGlobalProductAssociation;
