"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetProductResponseDataSizeChartImage = void 0;
var Product202309GetProductResponseDataSizeChartImage = /** @class */ (function () {
    function Product202309GetProductResponseDataSizeChartImage() {
    }
    Product202309GetProductResponseDataSizeChartImage.getAttributeTypeMap = function () {
        return Product202309GetProductResponseDataSizeChartImage.attributeTypeMap;
    };
    Product202309GetProductResponseDataSizeChartImage.discriminator = undefined;
    Product202309GetProductResponseDataSizeChartImage.attributeTypeMap = [
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "thumbUrls",
            "baseName": "thumb_urls",
            "type": "Array<string>"
        },
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string"
        },
        {
            "name": "urls",
            "baseName": "urls",
            "type": "Array<string>"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        }
    ];
    return Product202309GetProductResponseDataSizeChartImage;
}());
exports.Product202309GetProductResponseDataSizeChartImage = Product202309GetProductResponseDataSizeChartImage;
