"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetProductResponseDataVideo = void 0;
var Product202309GetProductResponseDataVideo = /** @class */ (function () {
    function Product202309GetProductResponseDataVideo() {
    }
    Product202309GetProductResponseDataVideo.getAttributeTypeMap = function () {
        return Product202309GetProductResponseDataVideo.attributeTypeMap;
    };
    Product202309GetProductResponseDataVideo.discriminator = undefined;
    Product202309GetProductResponseDataVideo.attributeTypeMap = [
        {
            "name": "coverUrl",
            "baseName": "cover_url",
            "type": "string"
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "string"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        }
    ];
    return Product202309GetProductResponseDataVideo;
}());
exports.Product202309GetProductResponseDataVideo = Product202309GetProductResponseDataVideo;
