"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetProductResponseDataCertificationsFiles = void 0;
var Product202309GetProductResponseDataCertificationsFiles = /** @class */ (function () {
    function Product202309GetProductResponseDataCertificationsFiles() {
    }
    Product202309GetProductResponseDataCertificationsFiles.getAttributeTypeMap = function () {
        return Product202309GetProductResponseDataCertificationsFiles.attributeTypeMap;
    };
    Product202309GetProductResponseDataCertificationsFiles.discriminator = undefined;
    Product202309GetProductResponseDataCertificationsFiles.attributeTypeMap = [
        {
            "name": "format",
            "baseName": "format",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "urls",
            "baseName": "urls",
            "type": "Array<string>"
        }
    ];
    return Product202309GetProductResponseDataCertificationsFiles;
}());
exports.Product202309GetProductResponseDataCertificationsFiles = Product202309GetProductResponseDataCertificationsFiles;
