"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetProductResponseDataSkusSalesAttributes = void 0;
var Product202309GetProductResponseDataSkusSalesAttributes = /** @class */ (function () {
    function Product202309GetProductResponseDataSkusSalesAttributes() {
    }
    Product202309GetProductResponseDataSkusSalesAttributes.getAttributeTypeMap = function () {
        return Product202309GetProductResponseDataSkusSalesAttributes.attributeTypeMap;
    };
    Product202309GetProductResponseDataSkusSalesAttributes.discriminator = undefined;
    Product202309GetProductResponseDataSkusSalesAttributes.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "skuImg",
            "baseName": "sku_img",
            "type": "Product202309GetProductResponseDataSkusSalesAttributesSkuImg"
        },
        {
            "name": "supplementarySkuImages",
            "baseName": "supplementary_sku_images",
            "type": "Array<Product202309GetProductResponseDataSkusSalesAttributesSupplementarySkuImages>"
        },
        {
            "name": "valueId",
            "baseName": "value_id",
            "type": "string"
        },
        {
            "name": "valueName",
            "baseName": "value_name",
            "type": "string"
        }
    ];
    return Product202309GetProductResponseDataSkusSalesAttributes;
}());
exports.Product202309GetProductResponseDataSkusSalesAttributes = Product202309GetProductResponseDataSkusSalesAttributes;
