"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309GetProductResponseDataProductFamilies = void 0;
var Product202309GetProductResponseDataProductFamilies = /** @class */ (function () {
    function Product202309GetProductResponseDataProductFamilies() {
    }
    Product202309GetProductResponseDataProductFamilies.getAttributeTypeMap = function () {
        return Product202309GetProductResponseDataProductFamilies.attributeTypeMap;
    };
    Product202309GetProductResponseDataProductFamilies.discriminator = undefined;
    Product202309GetProductResponseDataProductFamilies.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "products",
            "baseName": "products",
            "type": "Array<Product202309GetProductResponseDataProductFamiliesProducts>"
        }
    ];
    return Product202309GetProductResponseDataProductFamilies;
}());
exports.Product202309GetProductResponseDataProductFamilies = Product202309GetProductResponseDataProductFamilies;
