"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistribution = void 0;
var Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistribution = /** @class */ (function () {
    function Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistribution() {
    }
    Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistribution.getAttributeTypeMap = function () {
        return Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistribution.attributeTypeMap;
    };
    Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistribution.discriminator = undefined;
    Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistribution.attributeTypeMap = [
        {
            "name": "campaignInventory",
            "baseName": "campaign_inventory",
            "type": "Array<Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistributionCampaignInventory>"
        },
        {
            "name": "creatorInventory",
            "baseName": "creator_inventory",
            "type": "Array<Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistributionCreatorInventory>"
        },
        {
            "name": "inShopInventory",
            "baseName": "in_shop_inventory",
            "type": "Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistributionInShopInventory"
        }
    ];
    return Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistribution;
}());
exports.Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistribution = Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistribution;
