"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309InventorySearchResponseData = void 0;
var Product202309InventorySearchResponseData = /** @class */ (function () {
    function Product202309InventorySearchResponseData() {
    }
    Product202309InventorySearchResponseData.getAttributeTypeMap = function () {
        return Product202309InventorySearchResponseData.attributeTypeMap;
    };
    Product202309InventorySearchResponseData.discriminator = undefined;
    Product202309InventorySearchResponseData.attributeTypeMap = [
        {
            "name": "inventory",
            "baseName": "inventory",
            "type": "Array<Product202309InventorySearchResponseDataInventory>"
        }
    ];
    return Product202309InventorySearchResponseData;
}());
exports.Product202309InventorySearchResponseData = Product202309InventorySearchResponseData;
