"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistributionInShopInventory = void 0;
var Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistributionInShopInventory = /** @class */ (function () {
    function Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistributionInShopInventory() {
    }
    Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistributionInShopInventory.getAttributeTypeMap = function () {
        return Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistributionInShopInventory.attributeTypeMap;
    };
    Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistributionInShopInventory.discriminator = undefined;
    Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistributionInShopInventory.attributeTypeMap = [
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        }
    ];
    return Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistributionInShopInventory;
}());
exports.Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistributionInShopInventory = Product202309InventorySearchResponseDataInventorySkusTotalAvailableInventoryDistributionInShopInventory;
