"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309InventorySearchResponseDataInventorySkusWarehouseInventory = void 0;
var Product202309InventorySearchResponseDataInventorySkusWarehouseInventory = /** @class */ (function () {
    function Product202309InventorySearchResponseDataInventorySkusWarehouseInventory() {
    }
    Product202309InventorySearchResponseDataInventorySkusWarehouseInventory.getAttributeTypeMap = function () {
        return Product202309InventorySearchResponseDataInventorySkusWarehouseInventory.attributeTypeMap;
    };
    Product202309InventorySearchResponseDataInventorySkusWarehouseInventory.discriminator = undefined;
    Product202309InventorySearchResponseDataInventorySkusWarehouseInventory.attributeTypeMap = [
        {
            "name": "availableQuantity",
            "baseName": "available_quantity",
            "type": "number"
        },
        {
            "name": "committedQuantity",
            "baseName": "committed_quantity",
            "type": "number"
        },
        {
            "name": "warehouseId",
            "baseName": "warehouse_id",
            "type": "string"
        }
    ];
    return Product202309InventorySearchResponseDataInventorySkusWarehouseInventory;
}());
exports.Product202309InventorySearchResponseDataInventorySkusWarehouseInventory = Product202309InventorySearchResponseDataInventorySkusWarehouseInventory;
