"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309PartialEditProductRequestBodyVideo = void 0;
var Product202309PartialEditProductRequestBodyVideo = /** @class */ (function () {
    function Product202309PartialEditProductRequestBodyVideo() {
    }
    Product202309PartialEditProductRequestBodyVideo.getAttributeTypeMap = function () {
        return Product202309PartialEditProductRequestBodyVideo.attributeTypeMap;
    };
    Product202309PartialEditProductRequestBodyVideo.discriminator = undefined;
    Product202309PartialEditProductRequestBodyVideo.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }
    ];
    return Product202309PartialEditProductRequestBodyVideo;
}());
exports.Product202309PartialEditProductRequestBodyVideo = Product202309PartialEditProductRequestBodyVideo;
