"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309PartialEditProductResponseDataSkus = void 0;
var Product202309PartialEditProductResponseDataSkus = /** @class */ (function () {
    function Product202309PartialEditProductResponseDataSkus() {
    }
    Product202309PartialEditProductResponseDataSkus.getAttributeTypeMap = function () {
        return Product202309PartialEditProductResponseDataSkus.attributeTypeMap;
    };
    Product202309PartialEditProductResponseDataSkus.discriminator = undefined;
    Product202309PartialEditProductResponseDataSkus.attributeTypeMap = [
        {
            "name": "externalSkuId",
            "baseName": "external_sku_id",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "salesAttributes",
            "baseName": "sales_attributes",
            "type": "Array<Product202309PartialEditProductResponseDataSkusSalesAttributes>"
        },
        {
            "name": "sellerSku",
            "baseName": "seller_sku",
            "type": "string"
        }
    ];
    return Product202309PartialEditProductResponseDataSkus;
}());
exports.Product202309PartialEditProductResponseDataSkus = Product202309PartialEditProductResponseDataSkus;
