"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309PartialEditProductRequestBodySizeChartTemplate = void 0;
var Product202309PartialEditProductRequestBodySizeChartTemplate = /** @class */ (function () {
    function Product202309PartialEditProductRequestBodySizeChartTemplate() {
    }
    Product202309PartialEditProductRequestBodySizeChartTemplate.getAttributeTypeMap = function () {
        return Product202309PartialEditProductRequestBodySizeChartTemplate.attributeTypeMap;
    };
    Product202309PartialEditProductRequestBodySizeChartTemplate.discriminator = undefined;
    Product202309PartialEditProductRequestBodySizeChartTemplate.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }
    ];
    return Product202309PartialEditProductRequestBodySizeChartTemplate;
}());
exports.Product202309PartialEditProductRequestBodySizeChartTemplate = Product202309PartialEditProductRequestBodySizeChartTemplate;
