"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309PartialEditProductResponseDataAudit = void 0;
var Product202309PartialEditProductResponseDataAudit = /** @class */ (function () {
    function Product202309PartialEditProductResponseDataAudit() {
    }
    Product202309PartialEditProductResponseDataAudit.getAttributeTypeMap = function () {
        return Product202309PartialEditProductResponseDataAudit.attributeTypeMap;
    };
    Product202309PartialEditProductResponseDataAudit.discriminator = undefined;
    Product202309PartialEditProductResponseDataAudit.attributeTypeMap = [
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        }
    ];
    return Product202309PartialEditProductResponseDataAudit;
}());
exports.Product202309PartialEditProductResponseDataAudit = Product202309PartialEditProductResponseDataAudit;
