"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309PartialEditProductRequestBodyPackageDimensions = void 0;
var Product202309PartialEditProductRequestBodyPackageDimensions = /** @class */ (function () {
    function Product202309PartialEditProductRequestBodyPackageDimensions() {
    }
    Product202309PartialEditProductRequestBodyPackageDimensions.getAttributeTypeMap = function () {
        return Product202309PartialEditProductRequestBodyPackageDimensions.attributeTypeMap;
    };
    Product202309PartialEditProductRequestBodyPackageDimensions.discriminator = undefined;
    Product202309PartialEditProductRequestBodyPackageDimensions.attributeTypeMap = [
        {
            "name": "height",
            "baseName": "height",
            "type": "string"
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "string"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "string"
        }
    ];
    return Product202309PartialEditProductRequestBodyPackageDimensions;
}());
exports.Product202309PartialEditProductRequestBodyPackageDimensions = Product202309PartialEditProductRequestBodyPackageDimensions;
