"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309PublishGlobalProductResponseData = void 0;
var Product202309PublishGlobalProductResponseData = /** @class */ (function () {
    function Product202309PublishGlobalProductResponseData() {
    }
    Product202309PublishGlobalProductResponseData.getAttributeTypeMap = function () {
        return Product202309PublishGlobalProductResponseData.attributeTypeMap;
    };
    Product202309PublishGlobalProductResponseData.discriminator = undefined;
    Product202309PublishGlobalProductResponseData.attributeTypeMap = [
        {
            "name": "products",
            "baseName": "products",
            "type": "Array<Product202309PublishGlobalProductResponseDataProducts>"
        },
        {
            "name": "publishResult",
            "baseName": "publish_result",
            "type": "Array<Product202309PublishGlobalProductResponseDataPublishResult>"
        }
    ];
    return Product202309PublishGlobalProductResponseData;
}());
exports.Product202309PublishGlobalProductResponseData = Product202309PublishGlobalProductResponseData;
