"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309PublishGlobalProductResponseDataProductsSkus = void 0;
var Product202309PublishGlobalProductResponseDataProductsSkus = /** @class */ (function () {
    function Product202309PublishGlobalProductResponseDataProductsSkus() {
    }
    Product202309PublishGlobalProductResponseDataProductsSkus.getAttributeTypeMap = function () {
        return Product202309PublishGlobalProductResponseDataProductsSkus.attributeTypeMap;
    };
    Product202309PublishGlobalProductResponseDataProductsSkus.discriminator = undefined;
    Product202309PublishGlobalProductResponseDataProductsSkus.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "relatedGlobalSkuId",
            "baseName": "related_global_sku_id",
            "type": "string"
        },
        {
            "name": "saleAttributes",
            "baseName": "sale_attributes",
            "type": "Array<Product202309PublishGlobalProductResponseDataProductsSkusSaleAttributes>"
        },
        {
            "name": "sellerSku",
            "baseName": "seller_sku",
            "type": "string"
        }
    ];
    return Product202309PublishGlobalProductResponseDataProductsSkus;
}());
exports.Product202309PublishGlobalProductResponseDataProductsSkus = Product202309PublishGlobalProductResponseDataProductsSkus;
