"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309RecoverProductsRequestBody = void 0;
var Product202309RecoverProductsRequestBody = /** @class */ (function () {
    function Product202309RecoverProductsRequestBody() {
    }
    Product202309RecoverProductsRequestBody.getAttributeTypeMap = function () {
        return Product202309RecoverProductsRequestBody.attributeTypeMap;
    };
    Product202309RecoverProductsRequestBody.discriminator = undefined;
    Product202309RecoverProductsRequestBody.attributeTypeMap = [
        {
            "name": "productIds",
            "baseName": "product_ids",
            "type": "Array<string>"
        }
    ];
    return Product202309RecoverProductsRequestBody;
}());
exports.Product202309RecoverProductsRequestBody = Product202309RecoverProductsRequestBody;
