"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309RecommendCategoryResponseDataCategories = void 0;
var Product202309RecommendCategoryResponseDataCategories = /** @class */ (function () {
    function Product202309RecommendCategoryResponseDataCategories() {
    }
    Product202309RecommendCategoryResponseDataCategories.getAttributeTypeMap = function () {
        return Product202309RecommendCategoryResponseDataCategories.attributeTypeMap;
    };
    Product202309RecommendCategoryResponseDataCategories.discriminator = undefined;
    Product202309RecommendCategoryResponseDataCategories.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "isLeaf",
            "baseName": "is_leaf",
            "type": "boolean"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "permissionStatuses",
            "baseName": "permission_statuses",
            "type": "Array<string>"
        }
    ];
    return Product202309RecommendCategoryResponseDataCategories;
}());
exports.Product202309RecommendCategoryResponseDataCategories = Product202309RecommendCategoryResponseDataCategories;
