"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309RecommendGlobalCategoriesResponseDataCategories = void 0;
var Product202309RecommendGlobalCategoriesResponseDataCategories = /** @class */ (function () {
    function Product202309RecommendGlobalCategoriesResponseDataCategories() {
    }
    Product202309RecommendGlobalCategoriesResponseDataCategories.getAttributeTypeMap = function () {
        return Product202309RecommendGlobalCategoriesResponseDataCategories.attributeTypeMap;
    };
    Product202309RecommendGlobalCategoriesResponseDataCategories.discriminator = undefined;
    Product202309RecommendGlobalCategoriesResponseDataCategories.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "isLeaf",
            "baseName": "is_leaf",
            "type": "boolean"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }
    ];
    return Product202309RecommendGlobalCategoriesResponseDataCategories;
}());
exports.Product202309RecommendGlobalCategoriesResponseDataCategories = Product202309RecommendGlobalCategoriesResponseDataCategories;
