"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309SearchGlobalProductsResponseData = void 0;
var Product202309SearchGlobalProductsResponseData = /** @class */ (function () {
    function Product202309SearchGlobalProductsResponseData() {
    }
    Product202309SearchGlobalProductsResponseData.getAttributeTypeMap = function () {
        return Product202309SearchGlobalProductsResponseData.attributeTypeMap;
    };
    Product202309SearchGlobalProductsResponseData.discriminator = undefined;
    Product202309SearchGlobalProductsResponseData.attributeTypeMap = [
        {
            "name": "globalProducts",
            "baseName": "global_products",
            "type": "Array<Product202309SearchGlobalProductsResponseDataGlobalProducts>"
        },
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }
    ];
    return Product202309SearchGlobalProductsResponseData;
}());
exports.Product202309SearchGlobalProductsResponseData = Product202309SearchGlobalProductsResponseData;
