"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309SearchGlobalProductsResponse = void 0;
var Product202309SearchGlobalProductsResponse = /** @class */ (function () {
    function Product202309SearchGlobalProductsResponse() {
    }
    Product202309SearchGlobalProductsResponse.getAttributeTypeMap = function () {
        return Product202309SearchGlobalProductsResponse.attributeTypeMap;
    };
    Product202309SearchGlobalProductsResponse.discriminator = undefined;
    Product202309SearchGlobalProductsResponse.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Product202309SearchGlobalProductsResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }
    ];
    return Product202309SearchGlobalProductsResponse;
}());
exports.Product202309SearchGlobalProductsResponse = Product202309SearchGlobalProductsResponse;
