"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309SearchProductsResponseDataProductsRecommendedCategories = void 0;
var Product202309SearchProductsResponseDataProductsRecommendedCategories = /** @class */ (function () {
    function Product202309SearchProductsResponseDataProductsRecommendedCategories() {
    }
    Product202309SearchProductsResponseDataProductsRecommendedCategories.getAttributeTypeMap = function () {
        return Product202309SearchProductsResponseDataProductsRecommendedCategories.attributeTypeMap;
    };
    Product202309SearchProductsResponseDataProductsRecommendedCategories.discriminator = undefined;
    Product202309SearchProductsResponseDataProductsRecommendedCategories.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "localName",
            "baseName": "local_name",
            "type": "string"
        }
    ];
    return Product202309SearchProductsResponseDataProductsRecommendedCategories;
}());
exports.Product202309SearchProductsResponseDataProductsRecommendedCategories = Product202309SearchProductsResponseDataProductsRecommendedCategories;
