"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309UpdateInventoryResponseDataErrors = void 0;
var Product202309UpdateInventoryResponseDataErrors = /** @class */ (function () {
    function Product202309UpdateInventoryResponseDataErrors() {
    }
    Product202309UpdateInventoryResponseDataErrors.getAttributeTypeMap = function () {
        return Product202309UpdateInventoryResponseDataErrors.attributeTypeMap;
    };
    Product202309UpdateInventoryResponseDataErrors.discriminator = undefined;
    Product202309UpdateInventoryResponseDataErrors.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "Product202309UpdateInventoryResponseDataErrorsDetail"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }
    ];
    return Product202309UpdateInventoryResponseDataErrors;
}());
exports.Product202309UpdateInventoryResponseDataErrors = Product202309UpdateInventoryResponseDataErrors;
