"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309UpdatePriceRequestBodySkus = void 0;
var Product202309UpdatePriceRequestBodySkus = /** @class */ (function () {
    function Product202309UpdatePriceRequestBodySkus() {
    }
    Product202309UpdatePriceRequestBodySkus.getAttributeTypeMap = function () {
        return Product202309UpdatePriceRequestBodySkus.attributeTypeMap;
    };
    Product202309UpdatePriceRequestBodySkus.discriminator = undefined;
    Product202309UpdatePriceRequestBodySkus.attributeTypeMap = [
        {
            "name": "externalListPrices",
            "baseName": "external_list_prices",
            "type": "Array<Product202309UpdatePriceRequestBodySkusExternalListPrices>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "listPrice",
            "baseName": "list_price",
            "type": "Product202309UpdatePriceRequestBodySkusListPrice"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "Product202309UpdatePriceRequestBodySkusPrice"
        }
    ];
    return Product202309UpdatePriceRequestBodySkus;
}());
exports.Product202309UpdatePriceRequestBodySkus = Product202309UpdatePriceRequestBodySkus;
