"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309UpdateInventoryResponseData = void 0;
var Product202309UpdateInventoryResponseData = /** @class */ (function () {
    function Product202309UpdateInventoryResponseData() {
    }
    Product202309UpdateInventoryResponseData.getAttributeTypeMap = function () {
        return Product202309UpdateInventoryResponseData.attributeTypeMap;
    };
    Product202309UpdateInventoryResponseData.discriminator = undefined;
    Product202309UpdateInventoryResponseData.attributeTypeMap = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<Product202309UpdateInventoryResponseDataErrors>"
        }
    ];
    return Product202309UpdateInventoryResponseData;
}());
exports.Product202309UpdateInventoryResponseData = Product202309UpdateInventoryResponseData;
