"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309UpdateInventoryRequestBody = void 0;
var Product202309UpdateInventoryRequestBody = /** @class */ (function () {
    function Product202309UpdateInventoryRequestBody() {
    }
    Product202309UpdateInventoryRequestBody.getAttributeTypeMap = function () {
        return Product202309UpdateInventoryRequestBody.attributeTypeMap;
    };
    Product202309UpdateInventoryRequestBody.discriminator = undefined;
    Product202309UpdateInventoryRequestBody.attributeTypeMap = [
        {
            "name": "skus",
            "baseName": "skus",
            "type": "Array<Product202309UpdateInventoryRequestBodySkus>"
        }
    ];
    return Product202309UpdateInventoryRequestBody;
}());
exports.Product202309UpdateInventoryRequestBody = Product202309UpdateInventoryRequestBody;
