"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309UpdateInventoryRequestBodySkus = void 0;
var Product202309UpdateInventoryRequestBodySkus = /** @class */ (function () {
    function Product202309UpdateInventoryRequestBodySkus() {
    }
    Product202309UpdateInventoryRequestBodySkus.getAttributeTypeMap = function () {
        return Product202309UpdateInventoryRequestBodySkus.attributeTypeMap;
    };
    Product202309UpdateInventoryRequestBodySkus.discriminator = undefined;
    Product202309UpdateInventoryRequestBodySkus.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "inventory",
            "baseName": "inventory",
            "type": "Array<Product202309UpdateInventoryRequestBodySkusInventory>"
        }
    ];
    return Product202309UpdateInventoryRequestBodySkus;
}());
exports.Product202309UpdateInventoryRequestBodySkus = Product202309UpdateInventoryRequestBodySkus;
