"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202309UpdateInventoryRequestBodySkusInventory = void 0;
var Product202309UpdateInventoryRequestBodySkusInventory = /** @class */ (function () {
    function Product202309UpdateInventoryRequestBodySkusInventory() {
    }
    Product202309UpdateInventoryRequestBodySkusInventory.getAttributeTypeMap = function () {
        return Product202309UpdateInventoryRequestBodySkusInventory.attributeTypeMap;
    };
    Product202309UpdateInventoryRequestBodySkusInventory.discriminator = undefined;
    Product202309UpdateInventoryRequestBodySkusInventory.attributeTypeMap = [
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "warehouseId",
            "baseName": "warehouse_id",
            "type": "string"
        }
    ];
    return Product202309UpdateInventoryRequestBodySkusInventory;
}());
exports.Product202309UpdateInventoryRequestBodySkusInventory = Product202309UpdateInventoryRequestBodySkusInventory;
