"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesDimension = void 0;
var SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesDimension = /** @class */ (function () {
    function SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesDimension() {
    }
    SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesDimension.getAttributeTypeMap = function () {
        return SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesDimension.attributeTypeMap;
    };
    SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesDimension.discriminator = undefined;
    SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesDimension.attributeTypeMap = [
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        }
    ];
    return SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesDimension;
}());
exports.SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesDimension = SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesDimension;
