"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesSkus = void 0;
var SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesSkus = /** @class */ (function () {
    function SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesSkus() {
    }
    SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesSkus.getAttributeTypeMap = function () {
        return SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesSkus.attributeTypeMap;
    };
    SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesSkus.discriminator = undefined;
    SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesSkus.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        }
    ];
    return SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesSkus;
}());
exports.SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesSkus = SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesSkus;
