"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesWeight = void 0;
var SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesWeight = /** @class */ (function () {
    function SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesWeight() {
    }
    SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesWeight.getAttributeTypeMap = function () {
        return SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesWeight.attributeTypeMap;
    };
    SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesWeight.discriminator = undefined;
    SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesWeight.attributeTypeMap = [
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number"
        }
    ];
    return SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesWeight;
}());
exports.SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesWeight = SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesWeight;
