"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.SupplyChain202309ConfirmPackageShipmentResponseDataErrorsDetail = void 0;
var SupplyChain202309ConfirmPackageShipmentResponseDataErrorsDetail = /** @class */ (function () {
    function SupplyChain202309ConfirmPackageShipmentResponseDataErrorsDetail() {
    }
    SupplyChain202309ConfirmPackageShipmentResponseDataErrorsDetail.getAttributeTypeMap = function () {
        return SupplyChain202309ConfirmPackageShipmentResponseDataErrorsDetail.attributeTypeMap;
    };
    SupplyChain202309ConfirmPackageShipmentResponseDataErrorsDetail.discriminator = undefined;
    SupplyChain202309ConfirmPackageShipmentResponseDataErrorsDetail.attributeTypeMap = [
        {
            "name": "packageId",
            "baseName": "package_id",
            "type": "string"
        }
    ];
    return SupplyChain202309ConfirmPackageShipmentResponseDataErrorsDetail;
}());
exports.SupplyChain202309ConfirmPackageShipmentResponseDataErrorsDetail = SupplyChain202309ConfirmPackageShipmentResponseDataErrorsDetail;
