"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.SupplyChain202309ConfirmPackageShipmentResponseData = void 0;
var SupplyChain202309ConfirmPackageShipmentResponseData = /** @class */ (function () {
    function SupplyChain202309ConfirmPackageShipmentResponseData() {
    }
    SupplyChain202309ConfirmPackageShipmentResponseData.getAttributeTypeMap = function () {
        return SupplyChain202309ConfirmPackageShipmentResponseData.attributeTypeMap;
    };
    SupplyChain202309ConfirmPackageShipmentResponseData.discriminator = undefined;
    SupplyChain202309ConfirmPackageShipmentResponseData.attributeTypeMap = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<SupplyChain202309ConfirmPackageShipmentResponseDataErrors>"
        },
        {
            "name": "successPackages",
            "baseName": "success_packages",
            "type": "Array<string>"
        }
    ];
    return SupplyChain202309ConfirmPackageShipmentResponseData;
}());
exports.SupplyChain202309ConfirmPackageShipmentResponseData = SupplyChain202309ConfirmPackageShipmentResponseData;
