"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Fulfillment202502UploadInvoiceRequestBodyInvoices = void 0;
var Fulfillment202502UploadInvoiceRequestBodyInvoices = /** @class */ (function () {
    function Fulfillment202502UploadInvoiceRequestBodyInvoices() {
    }
    Fulfillment202502UploadInvoiceRequestBodyInvoices.getAttributeTypeMap = function () {
        return Fulfillment202502UploadInvoiceRequestBodyInvoices.attributeTypeMap;
    };
    Fulfillment202502UploadInvoiceRequestBodyInvoices.discriminator = undefined;
    Fulfillment202502UploadInvoiceRequestBodyInvoices.attributeTypeMap = [
        {
            "name": "file",
            "baseName": "file",
            "type": "string"
        },
        {
            "name": "fileType",
            "baseName": "file_type",
            "type": "string"
        },
        {
            "name": "orderIds",
            "baseName": "order_ids",
            "type": "Array<string>"
        },
        {
            "name": "packageId",
            "baseName": "package_id",
            "type": "string"
        }
    ];
    return Fulfillment202502UploadInvoiceRequestBodyInvoices;
}());
exports.Fulfillment202502UploadInvoiceRequestBodyInvoices = Fulfillment202502UploadInvoiceRequestBodyInvoices;
