"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Logistics202309GetGlobalSellerWarehouseResponseData = void 0;
var Logistics202309GetGlobalSellerWarehouseResponseData = /** @class */ (function () {
    function Logistics202309GetGlobalSellerWarehouseResponseData() {
    }
    Logistics202309GetGlobalSellerWarehouseResponseData.getAttributeTypeMap = function () {
        return Logistics202309GetGlobalSellerWarehouseResponseData.attributeTypeMap;
    };
    Logistics202309GetGlobalSellerWarehouseResponseData.discriminator = undefined;
    Logistics202309GetGlobalSellerWarehouseResponseData.attributeTypeMap = [
        {
            "name": "globalWarehouses",
            "baseName": "global_warehouses",
            "type": "Array<Logistics202309GetGlobalSellerWarehouseResponseDataGlobalWarehouses>"
        }
    ];
    return Logistics202309GetGlobalSellerWarehouseResponseData;
}());
exports.Logistics202309GetGlobalSellerWarehouseResponseData = Logistics202309GetGlobalSellerWarehouseResponseData;
