"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Logistics202309GetShippingProvidersResponseData = void 0;
var Logistics202309GetShippingProvidersResponseData = /** @class */ (function () {
    function Logistics202309GetShippingProvidersResponseData() {
    }
    Logistics202309GetShippingProvidersResponseData.getAttributeTypeMap = function () {
        return Logistics202309GetShippingProvidersResponseData.attributeTypeMap;
    };
    Logistics202309GetShippingProvidersResponseData.discriminator = undefined;
    Logistics202309GetShippingProvidersResponseData.attributeTypeMap = [
        {
            "name": "shippingProviders",
            "baseName": "shipping_providers",
            "type": "Array<Logistics202309GetShippingProvidersResponseDataShippingProviders>"
        }
    ];
    return Logistics202309GetShippingProvidersResponseData;
}());
exports.Logistics202309GetShippingProvidersResponseData = Logistics202309GetShippingProvidersResponseData;
