"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Logistics202309GetWarehouseListResponseData = void 0;
var Logistics202309GetWarehouseListResponseData = /** @class */ (function () {
    function Logistics202309GetWarehouseListResponseData() {
    }
    Logistics202309GetWarehouseListResponseData.getAttributeTypeMap = function () {
        return Logistics202309GetWarehouseListResponseData.attributeTypeMap;
    };
    Logistics202309GetWarehouseListResponseData.discriminator = undefined;
    Logistics202309GetWarehouseListResponseData.attributeTypeMap = [
        {
            "name": "warehouses",
            "baseName": "warehouses",
            "type": "Array<Logistics202309GetWarehouseListResponseDataWarehouses>"
        }
    ];
    return Logistics202309GetWarehouseListResponseData;
}());
exports.Logistics202309GetWarehouseListResponseData = Logistics202309GetWarehouseListResponseData;
