"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Logistics202309GetWarehouseListResponseDataWarehousesAddressGeolocation = void 0;
var Logistics202309GetWarehouseListResponseDataWarehousesAddressGeolocation = /** @class */ (function () {
    function Logistics202309GetWarehouseListResponseDataWarehousesAddressGeolocation() {
    }
    Logistics202309GetWarehouseListResponseDataWarehousesAddressGeolocation.getAttributeTypeMap = function () {
        return Logistics202309GetWarehouseListResponseDataWarehousesAddressGeolocation.attributeTypeMap;
    };
    Logistics202309GetWarehouseListResponseDataWarehousesAddressGeolocation.discriminator = undefined;
    Logistics202309GetWarehouseListResponseDataWarehousesAddressGeolocation.attributeTypeMap = [
        {
            "name": "latitude",
            "baseName": "latitude",
            "type": "string"
        },
        {
            "name": "longitude",
            "baseName": "longitude",
            "type": "string"
        }
    ];
    return Logistics202309GetWarehouseListResponseDataWarehousesAddressGeolocation;
}());
exports.Logistics202309GetWarehouseListResponseDataWarehousesAddressGeolocation = Logistics202309GetWarehouseListResponseDataWarehousesAddressGeolocation;
