"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsDimensionLimit = void 0;
var Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsDimensionLimit = /** @class */ (function () {
    function Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsDimensionLimit() {
    }
    Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsDimensionLimit.getAttributeTypeMap = function () {
        return Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsDimensionLimit.attributeTypeMap;
    };
    Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsDimensionLimit.discriminator = undefined;
    Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsDimensionLimit.attributeTypeMap = [
        {
            "name": "maxHeight",
            "baseName": "max_height",
            "type": "number"
        },
        {
            "name": "maxLength",
            "baseName": "max_length",
            "type": "number"
        },
        {
            "name": "maxWidth",
            "baseName": "max_width",
            "type": "number"
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "string"
        }
    ];
    return Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsDimensionLimit;
}());
exports.Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsDimensionLimit = Logistics202309GetWarehouseDeliveryOptionsResponseDataDeliveryOptionsDimensionLimit;
