"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Authorization202309GetAuthorizedShopsResponse = void 0;
var Authorization202309GetAuthorizedShopsResponse = /** @class */ (function () {
    function Authorization202309GetAuthorizedShopsResponse() {
    }
    Authorization202309GetAuthorizedShopsResponse.getAttributeTypeMap = function () {
        return Authorization202309GetAuthorizedShopsResponse.attributeTypeMap;
    };
    Authorization202309GetAuthorizedShopsResponse.discriminator = undefined;
    Authorization202309GetAuthorizedShopsResponse.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Authorization202309GetAuthorizedShopsResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }
    ];
    return Authorization202309GetAuthorizedShopsResponse;
}());
exports.Authorization202309GetAuthorizedShopsResponse = Authorization202309GetAuthorizedShopsResponse;
