"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202401ListingSchemasResponseDataListingSchemasFileds = void 0;
var Product202401ListingSchemasResponseDataListingSchemasFileds = /** @class */ (function () {
    function Product202401ListingSchemasResponseDataListingSchemasFileds() {
    }
    Product202401ListingSchemasResponseDataListingSchemasFileds.getAttributeTypeMap = function () {
        return Product202401ListingSchemasResponseDataListingSchemasFileds.attributeTypeMap;
    };
    Product202401ListingSchemasResponseDataListingSchemasFileds.discriminator = undefined;
    Product202401ListingSchemasResponseDataListingSchemasFileds.attributeTypeMap = [
        {
            "name": "complexValues",
            "baseName": "complex_values",
            "type": "Array<Product202401ListingSchemasResponseDataListingSchemasFiledsComplexValues>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<Product202401ListingSchemasResponseDataListingSchemasFiledsOptions>"
        },
        {
            "name": "rules",
            "baseName": "rules",
            "type": "Array<Product202401ListingSchemasResponseDataListingSchemasFiledsRules>"
        }
    ];
    return Product202401ListingSchemasResponseDataListingSchemasFileds;
}());
exports.Product202401ListingSchemasResponseDataListingSchemasFileds = Product202401ListingSchemasResponseDataListingSchemasFileds;
