"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202401ListingSchemasResponseDataListingSchemasFiledsOptions = void 0;
var Product202401ListingSchemasResponseDataListingSchemasFiledsOptions = /** @class */ (function () {
    function Product202401ListingSchemasResponseDataListingSchemasFiledsOptions() {
    }
    Product202401ListingSchemasResponseDataListingSchemasFiledsOptions.getAttributeTypeMap = function () {
        return Product202401ListingSchemasResponseDataListingSchemasFiledsOptions.attributeTypeMap;
    };
    Product202401ListingSchemasResponseDataListingSchemasFiledsOptions.discriminator = undefined;
    Product202401ListingSchemasResponseDataListingSchemasFiledsOptions.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }
    ];
    return Product202401ListingSchemasResponseDataListingSchemasFiledsOptions;
}());
exports.Product202401ListingSchemasResponseDataListingSchemasFiledsOptions = Product202401ListingSchemasResponseDataListingSchemasFiledsOptions;
