"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202401ListingSchemasResponseDataErrorsDetail = void 0;
var Product202401ListingSchemasResponseDataErrorsDetail = /** @class */ (function () {
    function Product202401ListingSchemasResponseDataErrorsDetail() {
    }
    Product202401ListingSchemasResponseDataErrorsDetail.getAttributeTypeMap = function () {
        return Product202401ListingSchemasResponseDataErrorsDetail.attributeTypeMap;
    };
    Product202401ListingSchemasResponseDataErrorsDetail.discriminator = undefined;
    Product202401ListingSchemasResponseDataErrorsDetail.attributeTypeMap = [
        {
            "name": "categoryId",
            "baseName": "category_id",
            "type": "number"
        }
    ];
    return Product202401ListingSchemasResponseDataErrorsDetail;
}());
exports.Product202401ListingSchemasResponseDataErrorsDetail = Product202401ListingSchemasResponseDataErrorsDetail;
