"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.CustomerService202309CreateConversationRequestBody = void 0;
var CustomerService202309CreateConversationRequestBody = /** @class */ (function () {
    function CustomerService202309CreateConversationRequestBody() {
    }
    CustomerService202309CreateConversationRequestBody.getAttributeTypeMap = function () {
        return CustomerService202309CreateConversationRequestBody.attributeTypeMap;
    };
    CustomerService202309CreateConversationRequestBody.discriminator = undefined;
    CustomerService202309CreateConversationRequestBody.attributeTypeMap = [
        {
            "name": "buyerUserId",
            "baseName": "buyer_user_id",
            "type": "string"
        }
    ];
    return CustomerService202309CreateConversationRequestBody;
}());
exports.CustomerService202309CreateConversationRequestBody = CustomerService202309CreateConversationRequestBody;
