"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.CustomerService202309GetAgentSettingsResponseData = void 0;
var CustomerService202309GetAgentSettingsResponseData = /** @class */ (function () {
    function CustomerService202309GetAgentSettingsResponseData() {
    }
    CustomerService202309GetAgentSettingsResponseData.getAttributeTypeMap = function () {
        return CustomerService202309GetAgentSettingsResponseData.attributeTypeMap;
    };
    CustomerService202309GetAgentSettingsResponseData.discriminator = undefined;
    CustomerService202309GetAgentSettingsResponseData.attributeTypeMap = [
        {
            "name": "canAcceptChat",
            "baseName": "can_accept_chat",
            "type": "boolean"
        }
    ];
    return CustomerService202309GetAgentSettingsResponseData;
}());
exports.CustomerService202309GetAgentSettingsResponseData = CustomerService202309GetAgentSettingsResponseData;
