"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.CustomerService202309GetAgentSettingsResponse = void 0;
var CustomerService202309GetAgentSettingsResponse = /** @class */ (function () {
    function CustomerService202309GetAgentSettingsResponse() {
    }
    CustomerService202309GetAgentSettingsResponse.getAttributeTypeMap = function () {
        return CustomerService202309GetAgentSettingsResponse.attributeTypeMap;
    };
    CustomerService202309GetAgentSettingsResponse.discriminator = undefined;
    CustomerService202309GetAgentSettingsResponse.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "CustomerService202309GetAgentSettingsResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }
    ];
    return CustomerService202309GetAgentSettingsResponse;
}());
exports.CustomerService202309GetAgentSettingsResponse = CustomerService202309GetAgentSettingsResponse;
