"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.CustomerService202309GetConversationMessagesResponse = void 0;
var CustomerService202309GetConversationMessagesResponse = /** @class */ (function () {
    function CustomerService202309GetConversationMessagesResponse() {
    }
    CustomerService202309GetConversationMessagesResponse.getAttributeTypeMap = function () {
        return CustomerService202309GetConversationMessagesResponse.attributeTypeMap;
    };
    CustomerService202309GetConversationMessagesResponse.discriminator = undefined;
    CustomerService202309GetConversationMessagesResponse.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "CustomerService202309GetConversationMessagesResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }
    ];
    return CustomerService202309GetConversationMessagesResponse;
}());
exports.CustomerService202309GetConversationMessagesResponse = CustomerService202309GetConversationMessagesResponse;
