"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.CustomerService202309GetConversationsResponseDataConversationsParticipants = void 0;
var CustomerService202309GetConversationsResponseDataConversationsParticipants = /** @class */ (function () {
    function CustomerService202309GetConversationsResponseDataConversationsParticipants() {
    }
    CustomerService202309GetConversationsResponseDataConversationsParticipants.getAttributeTypeMap = function () {
        return CustomerService202309GetConversationsResponseDataConversationsParticipants.attributeTypeMap;
    };
    CustomerService202309GetConversationsResponseDataConversationsParticipants.discriminator = undefined;
    CustomerService202309GetConversationsResponseDataConversationsParticipants.attributeTypeMap = [
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "string"
        },
        {
            "name": "buyerPlatform",
            "baseName": "buyer_platform",
            "type": "string"
        },
        {
            "name": "imUserId",
            "baseName": "im_user_id",
            "type": "string"
        },
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string"
        }
    ];
    return CustomerService202309GetConversationsResponseDataConversationsParticipants;
}());
exports.CustomerService202309GetConversationsResponseDataConversationsParticipants = CustomerService202309GetConversationsResponseDataConversationsParticipants;
