"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.CustomerService202309GetConversationMessagesResponseDataMessages = void 0;
var CustomerService202309GetConversationMessagesResponseDataMessages = /** @class */ (function () {
    function CustomerService202309GetConversationMessagesResponseDataMessages() {
    }
    CustomerService202309GetConversationMessagesResponseDataMessages.getAttributeTypeMap = function () {
        return CustomerService202309GetConversationMessagesResponseDataMessages.attributeTypeMap;
    };
    CustomerService202309GetConversationMessagesResponseDataMessages.discriminator = undefined;
    CustomerService202309GetConversationMessagesResponseDataMessages.attributeTypeMap = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "string"
        },
        {
            "name": "isVisible",
            "baseName": "is_visible",
            "type": "boolean"
        },
        {
            "name": "sender",
            "baseName": "sender",
            "type": "CustomerService202309GetConversationMessagesResponseDataMessagesSender"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }
    ];
    return CustomerService202309GetConversationMessagesResponseDataMessages;
}());
exports.CustomerService202309GetConversationMessagesResponseDataMessages = CustomerService202309GetConversationMessagesResponseDataMessages;
