"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.CustomerService202309SendMessageRequestBody = void 0;
var CustomerService202309SendMessageRequestBody = /** @class */ (function () {
    function CustomerService202309SendMessageRequestBody() {
    }
    CustomerService202309SendMessageRequestBody.getAttributeTypeMap = function () {
        return CustomerService202309SendMessageRequestBody.attributeTypeMap;
    };
    CustomerService202309SendMessageRequestBody.discriminator = undefined;
    CustomerService202309SendMessageRequestBody.attributeTypeMap = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }
    ];
    return CustomerService202309SendMessageRequestBody;
}());
exports.CustomerService202309SendMessageRequestBody = CustomerService202309SendMessageRequestBody;
