"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.CustomerService202407GetCustomerServicePerformanceResponseDataPerformance = void 0;
var CustomerService202407GetCustomerServicePerformanceResponseDataPerformance = /** @class */ (function () {
    function CustomerService202407GetCustomerServicePerformanceResponseDataPerformance() {
    }
    CustomerService202407GetCustomerServicePerformanceResponseDataPerformance.getAttributeTypeMap = function () {
        return CustomerService202407GetCustomerServicePerformanceResponseDataPerformance.attributeTypeMap;
    };
    CustomerService202407GetCustomerServicePerformanceResponseDataPerformance.discriminator = undefined;
    CustomerService202407GetCustomerServicePerformanceResponseDataPerformance.attributeTypeMap = [
        {
            "name": "responsePercentage",
            "baseName": "response_percentage",
            "type": "string"
        },
        {
            "name": "responseTimeMins",
            "baseName": "response_time_mins",
            "type": "string"
        },
        {
            "name": "satisfactionPercentage",
            "baseName": "satisfaction_percentage",
            "type": "string"
        },
        {
            "name": "supportSessionCount",
            "baseName": "support_session_count",
            "type": "number"
        }
    ];
    return CustomerService202407GetCustomerServicePerformanceResponseDataPerformance;
}());
exports.CustomerService202407GetCustomerServicePerformanceResponseDataPerformance = CustomerService202407GetCustomerServicePerformanceResponseDataPerformance;
