"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.CustomerService202407GetCustomerServicePerformanceResponse = void 0;
var CustomerService202407GetCustomerServicePerformanceResponse = /** @class */ (function () {
    function CustomerService202407GetCustomerServicePerformanceResponse() {
    }
    CustomerService202407GetCustomerServicePerformanceResponse.getAttributeTypeMap = function () {
        return CustomerService202407GetCustomerServicePerformanceResponse.attributeTypeMap;
    };
    CustomerService202407GetCustomerServicePerformanceResponse.discriminator = undefined;
    CustomerService202407GetCustomerServicePerformanceResponse.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "CustomerService202407GetCustomerServicePerformanceResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }
    ];
    return CustomerService202407GetCustomerServicePerformanceResponse;
}());
exports.CustomerService202407GetCustomerServicePerformanceResponse = CustomerService202407GetCustomerServicePerformanceResponse;
