"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.CustomerService202407GetCustomerServicePerformanceResponseData = void 0;
var CustomerService202407GetCustomerServicePerformanceResponseData = /** @class */ (function () {
    function CustomerService202407GetCustomerServicePerformanceResponseData() {
    }
    CustomerService202407GetCustomerServicePerformanceResponseData.getAttributeTypeMap = function () {
        return CustomerService202407GetCustomerServicePerformanceResponseData.attributeTypeMap;
    };
    CustomerService202407GetCustomerServicePerformanceResponseData.discriminator = undefined;
    CustomerService202407GetCustomerServicePerformanceResponseData.attributeTypeMap = [
        {
            "name": "performance",
            "baseName": "performance",
            "type": "CustomerService202407GetCustomerServicePerformanceResponseDataPerformance"
        }
    ];
    return CustomerService202407GetCustomerServicePerformanceResponseData;
}());
exports.CustomerService202407GetCustomerServicePerformanceResponseData = CustomerService202407GetCustomerServicePerformanceResponseData;
