"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Order202309GetOrderListResponseDataOrdersPackages = void 0;
var Order202309GetOrderListResponseDataOrdersPackages = /** @class */ (function () {
    function Order202309GetOrderListResponseDataOrdersPackages() {
    }
    Order202309GetOrderListResponseDataOrdersPackages.getAttributeTypeMap = function () {
        return Order202309GetOrderListResponseDataOrdersPackages.attributeTypeMap;
    };
    Order202309GetOrderListResponseDataOrdersPackages.discriminator = undefined;
    Order202309GetOrderListResponseDataOrdersPackages.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }
    ];
    return Order202309GetOrderListResponseDataOrdersPackages;
}());
exports.Order202309GetOrderListResponseDataOrdersPackages = Order202309GetOrderListResponseDataOrdersPackages;
