"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Order202309GetOrderListResponseDataOrdersRecipientAddressDeliveryPreferences = void 0;
var Order202309GetOrderListResponseDataOrdersRecipientAddressDeliveryPreferences = /** @class */ (function () {
    function Order202309GetOrderListResponseDataOrdersRecipientAddressDeliveryPreferences() {
    }
    Order202309GetOrderListResponseDataOrdersRecipientAddressDeliveryPreferences.getAttributeTypeMap = function () {
        return Order202309GetOrderListResponseDataOrdersRecipientAddressDeliveryPreferences.attributeTypeMap;
    };
    Order202309GetOrderListResponseDataOrdersRecipientAddressDeliveryPreferences.discriminator = undefined;
    Order202309GetOrderListResponseDataOrdersRecipientAddressDeliveryPreferences.attributeTypeMap = [
        {
            "name": "dropOffLocation",
            "baseName": "drop_off_location",
            "type": "string"
        }
    ];
    return Order202309GetOrderListResponseDataOrdersRecipientAddressDeliveryPreferences;
}());
exports.Order202309GetOrderListResponseDataOrdersRecipientAddressDeliveryPreferences = Order202309GetOrderListResponseDataOrdersRecipientAddressDeliveryPreferences;
