"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Order202309GetOrderDetailResponseDataOrdersHandlingDuration = void 0;
var Order202309GetOrderDetailResponseDataOrdersHandlingDuration = /** @class */ (function () {
    function Order202309GetOrderDetailResponseDataOrdersHandlingDuration() {
    }
    Order202309GetOrderDetailResponseDataOrdersHandlingDuration.getAttributeTypeMap = function () {
        return Order202309GetOrderDetailResponseDataOrdersHandlingDuration.attributeTypeMap;
    };
    Order202309GetOrderDetailResponseDataOrdersHandlingDuration.discriminator = undefined;
    Order202309GetOrderDetailResponseDataOrdersHandlingDuration.attributeTypeMap = [
        {
            "name": "days",
            "baseName": "days",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }
    ];
    return Order202309GetOrderDetailResponseDataOrdersHandlingDuration;
}());
exports.Order202309GetOrderDetailResponseDataOrdersHandlingDuration = Order202309GetOrderDetailResponseDataOrdersHandlingDuration;
