"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Order202309GetOrderDetailResponseDataOrdersLineItemsCombinedListingSkus = void 0;
var Order202309GetOrderDetailResponseDataOrdersLineItemsCombinedListingSkus = /** @class */ (function () {
    function Order202309GetOrderDetailResponseDataOrdersLineItemsCombinedListingSkus() {
    }
    Order202309GetOrderDetailResponseDataOrdersLineItemsCombinedListingSkus.getAttributeTypeMap = function () {
        return Order202309GetOrderDetailResponseDataOrdersLineItemsCombinedListingSkus.attributeTypeMap;
    };
    Order202309GetOrderDetailResponseDataOrdersLineItemsCombinedListingSkus.discriminator = undefined;
    Order202309GetOrderDetailResponseDataOrdersLineItemsCombinedListingSkus.attributeTypeMap = [
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        },
        {
            "name": "sellerSku",
            "baseName": "seller_sku",
            "type": "string"
        },
        {
            "name": "skuCount",
            "baseName": "sku_count",
            "type": "number"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        }
    ];
    return Order202309GetOrderDetailResponseDataOrdersLineItemsCombinedListingSkus;
}());
exports.Order202309GetOrderDetailResponseDataOrdersLineItemsCombinedListingSkus = Order202309GetOrderDetailResponseDataOrdersLineItemsCombinedListingSkus;
