"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Order202309GetOrderDetailResponseData = void 0;
var Order202309GetOrderDetailResponseData = /** @class */ (function () {
    function Order202309GetOrderDetailResponseData() {
    }
    Order202309GetOrderDetailResponseData.getAttributeTypeMap = function () {
        return Order202309GetOrderDetailResponseData.attributeTypeMap;
    };
    Order202309GetOrderDetailResponseData.discriminator = undefined;
    Order202309GetOrderDetailResponseData.attributeTypeMap = [
        {
            "name": "orders",
            "baseName": "orders",
            "type": "Array<Order202309GetOrderDetailResponseDataOrders>"
        }
    ];
    return Order202309GetOrderDetailResponseData;
}());
exports.Order202309GetOrderDetailResponseData = Order202309GetOrderDetailResponseData;
