"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Order202309GetOrderListResponseDataOrdersRecipientAddressDistrictInfo = void 0;
var Order202309GetOrderListResponseDataOrdersRecipientAddressDistrictInfo = /** @class */ (function () {
    function Order202309GetOrderListResponseDataOrdersRecipientAddressDistrictInfo() {
    }
    Order202309GetOrderListResponseDataOrdersRecipientAddressDistrictInfo.getAttributeTypeMap = function () {
        return Order202309GetOrderListResponseDataOrdersRecipientAddressDistrictInfo.attributeTypeMap;
    };
    Order202309GetOrderListResponseDataOrdersRecipientAddressDistrictInfo.discriminator = undefined;
    Order202309GetOrderListResponseDataOrdersRecipientAddressDistrictInfo.attributeTypeMap = [
        {
            "name": "addressLevel",
            "baseName": "address_level",
            "type": "string"
        },
        {
            "name": "addressLevelName",
            "baseName": "address_level_name",
            "type": "string"
        },
        {
            "name": "addressName",
            "baseName": "address_name",
            "type": "string"
        }
    ];
    return Order202309GetOrderListResponseDataOrdersRecipientAddressDistrictInfo;
}());
exports.Order202309GetOrderListResponseDataOrdersRecipientAddressDistrictInfo = Order202309GetOrderListResponseDataOrdersRecipientAddressDistrictInfo;
