"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.DataReconciliation202309OrderStatusDataExchangeResponseData = void 0;
var DataReconciliation202309OrderStatusDataExchangeResponseData = /** @class */ (function () {
    function DataReconciliation202309OrderStatusDataExchangeResponseData() {
    }
    DataReconciliation202309OrderStatusDataExchangeResponseData.getAttributeTypeMap = function () {
        return DataReconciliation202309OrderStatusDataExchangeResponseData.attributeTypeMap;
    };
    DataReconciliation202309OrderStatusDataExchangeResponseData.discriminator = undefined;
    DataReconciliation202309OrderStatusDataExchangeResponseData.attributeTypeMap = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<DataReconciliation202309OrderStatusDataExchangeResponseDataErrors>"
        }
    ];
    return DataReconciliation202309OrderStatusDataExchangeResponseData;
}());
exports.DataReconciliation202309OrderStatusDataExchangeResponseData = DataReconciliation202309OrderStatusDataExchangeResponseData;
