"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.DataReconciliation202309OrderStatusDataExchangeResponse = void 0;
var DataReconciliation202309OrderStatusDataExchangeResponse = /** @class */ (function () {
    function DataReconciliation202309OrderStatusDataExchangeResponse() {
    }
    DataReconciliation202309OrderStatusDataExchangeResponse.getAttributeTypeMap = function () {
        return DataReconciliation202309OrderStatusDataExchangeResponse.attributeTypeMap;
    };
    DataReconciliation202309OrderStatusDataExchangeResponse.discriminator = undefined;
    DataReconciliation202309OrderStatusDataExchangeResponse.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "DataReconciliation202309OrderStatusDataExchangeResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }
    ];
    return DataReconciliation202309OrderStatusDataExchangeResponse;
}());
exports.DataReconciliation202309OrderStatusDataExchangeResponse = DataReconciliation202309OrderStatusDataExchangeResponse;
