"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202312SearchProductsResponseDataProductsSkusExternalListPrices = void 0;
var Product202312SearchProductsResponseDataProductsSkusExternalListPrices = /** @class */ (function () {
    function Product202312SearchProductsResponseDataProductsSkusExternalListPrices() {
    }
    Product202312SearchProductsResponseDataProductsSkusExternalListPrices.getAttributeTypeMap = function () {
        return Product202312SearchProductsResponseDataProductsSkusExternalListPrices.attributeTypeMap;
    };
    Product202312SearchProductsResponseDataProductsSkusExternalListPrices.discriminator = undefined;
    Product202312SearchProductsResponseDataProductsSkusExternalListPrices.attributeTypeMap = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string"
        }
    ];
    return Product202312SearchProductsResponseDataProductsSkusExternalListPrices;
}());
exports.Product202312SearchProductsResponseDataProductsSkusExternalListPrices = Product202312SearchProductsResponseDataProductsSkusExternalListPrices;
