"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202312SearchProductsResponseDataProductsIntegratedPlatformStatuses = void 0;
var Product202312SearchProductsResponseDataProductsIntegratedPlatformStatuses = /** @class */ (function () {
    function Product202312SearchProductsResponseDataProductsIntegratedPlatformStatuses() {
    }
    Product202312SearchProductsResponseDataProductsIntegratedPlatformStatuses.getAttributeTypeMap = function () {
        return Product202312SearchProductsResponseDataProductsIntegratedPlatformStatuses.attributeTypeMap;
    };
    Product202312SearchProductsResponseDataProductsIntegratedPlatformStatuses.discriminator = undefined;
    Product202312SearchProductsResponseDataProductsIntegratedPlatformStatuses.attributeTypeMap = [
        {
            "name": "platform",
            "baseName": "platform",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        }
    ];
    return Product202312SearchProductsResponseDataProductsIntegratedPlatformStatuses;
}());
exports.Product202312SearchProductsResponseDataProductsIntegratedPlatformStatuses = Product202312SearchProductsResponseDataProductsIntegratedPlatformStatuses;
