"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202312SearchGlobalProductsResponseDataGlobalProductsSkus = void 0;
var Product202312SearchGlobalProductsResponseDataGlobalProductsSkus = /** @class */ (function () {
    function Product202312SearchGlobalProductsResponseDataGlobalProductsSkus() {
    }
    Product202312SearchGlobalProductsResponseDataGlobalProductsSkus.getAttributeTypeMap = function () {
        return Product202312SearchGlobalProductsResponseDataGlobalProductsSkus.attributeTypeMap;
    };
    Product202312SearchGlobalProductsResponseDataGlobalProductsSkus.discriminator = undefined;
    Product202312SearchGlobalProductsResponseDataGlobalProductsSkus.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "sellerSku",
            "baseName": "seller_sku",
            "type": "string"
        }
    ];
    return Product202312SearchGlobalProductsResponseDataGlobalProductsSkus;
}());
exports.Product202312SearchGlobalProductsResponseDataGlobalProductsSkus = Product202312SearchGlobalProductsResponseDataGlobalProductsSkus;
