"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202505CreateImageTranslationTasksResponse = void 0;
var Product202505CreateImageTranslationTasksResponse = /** @class */ (function () {
    function Product202505CreateImageTranslationTasksResponse() {
    }
    Product202505CreateImageTranslationTasksResponse.getAttributeTypeMap = function () {
        return Product202505CreateImageTranslationTasksResponse.attributeTypeMap;
    };
    Product202505CreateImageTranslationTasksResponse.discriminator = undefined;
    Product202505CreateImageTranslationTasksResponse.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Product202505CreateImageTranslationTasksResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }
    ];
    return Product202505CreateImageTranslationTasksResponse;
}());
exports.Product202505CreateImageTranslationTasksResponse = Product202505CreateImageTranslationTasksResponse;
