"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202505CreateImageTranslationTasksResponseData = void 0;
var Product202505CreateImageTranslationTasksResponseData = /** @class */ (function () {
    function Product202505CreateImageTranslationTasksResponseData() {
    }
    Product202505CreateImageTranslationTasksResponseData.getAttributeTypeMap = function () {
        return Product202505CreateImageTranslationTasksResponseData.attributeTypeMap;
    };
    Product202505CreateImageTranslationTasksResponseData.discriminator = undefined;
    Product202505CreateImageTranslationTasksResponseData.attributeTypeMap = [
        {
            "name": "translationTasks",
            "baseName": "translation_tasks",
            "type": "Array<Product202505CreateImageTranslationTasksResponseDataTranslationTasks>"
        }
    ];
    return Product202505CreateImageTranslationTasksResponseData;
}());
exports.Product202505CreateImageTranslationTasksResponseData = Product202505CreateImageTranslationTasksResponseData;
