"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Authorization202401GetWidgetTokenResponseDataWidgetToken = void 0;
var Authorization202401GetWidgetTokenResponseDataWidgetToken = /** @class */ (function () {
    function Authorization202401GetWidgetTokenResponseDataWidgetToken() {
    }
    Authorization202401GetWidgetTokenResponseDataWidgetToken.getAttributeTypeMap = function () {
        return Authorization202401GetWidgetTokenResponseDataWidgetToken.attributeTypeMap;
    };
    Authorization202401GetWidgetTokenResponseDataWidgetToken.discriminator = undefined;
    Authorization202401GetWidgetTokenResponseDataWidgetToken.attributeTypeMap = [
        {
            "name": "expireAt",
            "baseName": "expire_at",
            "type": "number"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        }
    ];
    return Authorization202401GetWidgetTokenResponseDataWidgetToken;
}());
exports.Authorization202401GetWidgetTokenResponseDataWidgetToken = Authorization202401GetWidgetTokenResponseDataWidgetToken;
