"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202404OptimizedImagesRequestBodyImages = void 0;
var Product202404OptimizedImagesRequestBodyImages = /** @class */ (function () {
    function Product202404OptimizedImagesRequestBodyImages() {
    }
    Product202404OptimizedImagesRequestBodyImages.getAttributeTypeMap = function () {
        return Product202404OptimizedImagesRequestBodyImages.attributeTypeMap;
    };
    Product202404OptimizedImagesRequestBodyImages.discriminator = undefined;
    Product202404OptimizedImagesRequestBodyImages.attributeTypeMap = [
        {
            "name": "optimizationMode",
            "baseName": "optimization_mode",
            "type": "Array<string>"
        },
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string"
        }
    ];
    return Product202404OptimizedImagesRequestBodyImages;
}());
exports.Product202404OptimizedImagesRequestBodyImages = Product202404OptimizedImagesRequestBodyImages;
