"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202404OptimizedImagesResponseData = void 0;
var Product202404OptimizedImagesResponseData = /** @class */ (function () {
    function Product202404OptimizedImagesResponseData() {
    }
    Product202404OptimizedImagesResponseData.getAttributeTypeMap = function () {
        return Product202404OptimizedImagesResponseData.attributeTypeMap;
    };
    Product202404OptimizedImagesResponseData.discriminator = undefined;
    Product202404OptimizedImagesResponseData.attributeTypeMap = [
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<Product202404OptimizedImagesResponseDataImages>"
        }
    ];
    return Product202404OptimizedImagesResponseData;
}());
exports.Product202404OptimizedImagesResponseData = Product202404OptimizedImagesResponseData;
