"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202405GetProductsSEOWordsResponseDataProductsSeoWords = void 0;
var Product202405GetProductsSEOWordsResponseDataProductsSeoWords = /** @class */ (function () {
    function Product202405GetProductsSEOWordsResponseDataProductsSeoWords() {
    }
    Product202405GetProductsSEOWordsResponseDataProductsSeoWords.getAttributeTypeMap = function () {
        return Product202405GetProductsSEOWordsResponseDataProductsSeoWords.attributeTypeMap;
    };
    Product202405GetProductsSEOWordsResponseDataProductsSeoWords.discriminator = undefined;
    Product202405GetProductsSEOWordsResponseDataProductsSeoWords.attributeTypeMap = [
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        }
    ];
    return Product202405GetProductsSEOWordsResponseDataProductsSeoWords;
}());
exports.Product202405GetProductsSEOWordsResponseDataProductsSeoWords = Product202405GetProductsSEOWordsResponseDataProductsSeoWords;
