"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202405GetProductsSEOWordsResponseData = void 0;
var Product202405GetProductsSEOWordsResponseData = /** @class */ (function () {
    function Product202405GetProductsSEOWordsResponseData() {
    }
    Product202405GetProductsSEOWordsResponseData.getAttributeTypeMap = function () {
        return Product202405GetProductsSEOWordsResponseData.attributeTypeMap;
    };
    Product202405GetProductsSEOWordsResponseData.discriminator = undefined;
    Product202405GetProductsSEOWordsResponseData.attributeTypeMap = [
        {
            "name": "products",
            "baseName": "products",
            "type": "Array<Product202405GetProductsSEOWordsResponseDataProducts>"
        }
    ];
    return Product202405GetProductsSEOWordsResponseData;
}());
exports.Product202405GetProductsSEOWordsResponseData = Product202405GetProductsSEOWordsResponseData;
