"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems = void 0;
var Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems = /** @class */ (function () {
    function Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems() {
    }
    Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems.getAttributeTypeMap = function () {
        return Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems.attributeTypeMap;
    };
    Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems.discriminator = undefined;
    Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems.attributeTypeMap = [
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        }
    ];
    return Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems;
}());
exports.Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems = Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems;
