"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions = void 0;
var Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions = /** @class */ (function () {
    function Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions() {
    }
    Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions.getAttributeTypeMap = function () {
        return Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions.attributeTypeMap;
    };
    Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions.discriminator = undefined;
    Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions.attributeTypeMap = [
        {
            "name": "field",
            "baseName": "field",
            "type": "string"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems>"
        }
    ];
    return Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions;
}());
exports.Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions = Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions;
