"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionImages = void 0;
var Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionImages = /** @class */ (function () {
    function Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionImages() {
    }
    Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionImages.getAttributeTypeMap = function () {
        return Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionImages.attributeTypeMap;
    };
    Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionImages.discriminator = undefined;
    Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionImages.attributeTypeMap = [
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "optimizedUri",
            "baseName": "optimized_uri",
            "type": "string"
        },
        {
            "name": "optimizedUrl",
            "baseName": "optimized_url",
            "type": "string"
        },
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        }
    ];
    return Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionImages;
}());
exports.Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionImages = Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionImages;
