"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202405ProductInformationIssueDiagnosisResponseDataProducts = void 0;
var Product202405ProductInformationIssueDiagnosisResponseDataProducts = /** @class */ (function () {
    function Product202405ProductInformationIssueDiagnosisResponseDataProducts() {
    }
    Product202405ProductInformationIssueDiagnosisResponseDataProducts.getAttributeTypeMap = function () {
        return Product202405ProductInformationIssueDiagnosisResponseDataProducts.attributeTypeMap;
    };
    Product202405ProductInformationIssueDiagnosisResponseDataProducts.discriminator = undefined;
    Product202405ProductInformationIssueDiagnosisResponseDataProducts.attributeTypeMap = [
        {
            "name": "diagnoses",
            "baseName": "diagnoses",
            "type": "Array<Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnoses>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "listingQuality",
            "baseName": "listing_quality",
            "type": "Product202405ProductInformationIssueDiagnosisResponseDataProductsListingQuality"
        }
    ];
    return Product202405ProductInformationIssueDiagnosisResponseDataProducts;
}());
exports.Product202405ProductInformationIssueDiagnosisResponseDataProducts = Product202405ProductInformationIssueDiagnosisResponseDataProducts;
