"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionSeoWords = void 0;
var Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionSeoWords = /** @class */ (function () {
    function Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionSeoWords() {
    }
    Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionSeoWords.getAttributeTypeMap = function () {
        return Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionSeoWords.attributeTypeMap;
    };
    Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionSeoWords.discriminator = undefined;
    Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionSeoWords.attributeTypeMap = [
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        }
    ];
    return Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionSeoWords;
}());
exports.Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionSeoWords = Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestionSeoWords;
