"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnoses = void 0;
var Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnoses = /** @class */ (function () {
    function Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnoses() {
    }
    Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnoses.getAttributeTypeMap = function () {
        return Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnoses.attributeTypeMap;
    };
    Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnoses.discriminator = undefined;
    Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnoses.attributeTypeMap = [
        {
            "name": "diagnosisResults",
            "baseName": "diagnosis_results",
            "type": "Array<Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesDiagnosisResults>"
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "string"
        },
        {
            "name": "suggestion",
            "baseName": "suggestion",
            "type": "Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesSuggestion"
        }
    ];
    return Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnoses;
}());
exports.Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnoses = Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnoses;
