"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202502SearchProductsResponseDataProductsProductFamiliesProducts = void 0;
var Product202502SearchProductsResponseDataProductsProductFamiliesProducts = /** @class */ (function () {
    function Product202502SearchProductsResponseDataProductsProductFamiliesProducts() {
    }
    Product202502SearchProductsResponseDataProductsProductFamiliesProducts.getAttributeTypeMap = function () {
        return Product202502SearchProductsResponseDataProductsProductFamiliesProducts.attributeTypeMap;
    };
    Product202502SearchProductsResponseDataProductsProductFamiliesProducts.discriminator = undefined;
    Product202502SearchProductsResponseDataProductsProductFamiliesProducts.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }
    ];
    return Product202502SearchProductsResponseDataProductsProductFamiliesProducts;
}());
exports.Product202502SearchProductsResponseDataProductsProductFamiliesProducts = Product202502SearchProductsResponseDataProductsProductFamiliesProducts;
