"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202502SearchProductsResponseDataProductsProductFamilies = void 0;
var Product202502SearchProductsResponseDataProductsProductFamilies = /** @class */ (function () {
    function Product202502SearchProductsResponseDataProductsProductFamilies() {
    }
    Product202502SearchProductsResponseDataProductsProductFamilies.getAttributeTypeMap = function () {
        return Product202502SearchProductsResponseDataProductsProductFamilies.attributeTypeMap;
    };
    Product202502SearchProductsResponseDataProductsProductFamilies.discriminator = undefined;
    Product202502SearchProductsResponseDataProductsProductFamilies.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "products",
            "baseName": "products",
            "type": "Array<Product202502SearchProductsResponseDataProductsProductFamiliesProducts>"
        }
    ];
    return Product202502SearchProductsResponseDataProductsProductFamilies;
}());
exports.Product202502SearchProductsResponseDataProductsProductFamilies = Product202502SearchProductsResponseDataProductsProductFamilies;
