"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202502SearchProductsResponseDataProductsSkusPreSaleFulfillmentType = void 0;
var Product202502SearchProductsResponseDataProductsSkusPreSaleFulfillmentType = /** @class */ (function () {
    function Product202502SearchProductsResponseDataProductsSkusPreSaleFulfillmentType() {
    }
    Product202502SearchProductsResponseDataProductsSkusPreSaleFulfillmentType.getAttributeTypeMap = function () {
        return Product202502SearchProductsResponseDataProductsSkusPreSaleFulfillmentType.attributeTypeMap;
    };
    Product202502SearchProductsResponseDataProductsSkusPreSaleFulfillmentType.discriminator = undefined;
    Product202502SearchProductsResponseDataProductsSkusPreSaleFulfillmentType.attributeTypeMap = [
        {
            "name": "handlingDurationDays",
            "baseName": "handling_duration_days",
            "type": "number"
        },
        {
            "name": "releaseDate",
            "baseName": "release_date",
            "type": "number"
        }
    ];
    return Product202502SearchProductsResponseDataProductsSkusPreSaleFulfillmentType;
}());
exports.Product202502SearchProductsResponseDataProductsSkusPreSaleFulfillmentType = Product202502SearchProductsResponseDataProductsSkusPreSaleFulfillmentType;
