"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202502SearchProductsResponseDataProductsRecommendedCategories = void 0;
var Product202502SearchProductsResponseDataProductsRecommendedCategories = /** @class */ (function () {
    function Product202502SearchProductsResponseDataProductsRecommendedCategories() {
    }
    Product202502SearchProductsResponseDataProductsRecommendedCategories.getAttributeTypeMap = function () {
        return Product202502SearchProductsResponseDataProductsRecommendedCategories.attributeTypeMap;
    };
    Product202502SearchProductsResponseDataProductsRecommendedCategories.discriminator = undefined;
    Product202502SearchProductsResponseDataProductsRecommendedCategories.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "localName",
            "baseName": "local_name",
            "type": "string"
        }
    ];
    return Product202502SearchProductsResponseDataProductsRecommendedCategories;
}());
exports.Product202502SearchProductsResponseDataProductsRecommendedCategories = Product202502SearchProductsResponseDataProductsRecommendedCategories;
