"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Event202309GetShopWebhooksResponseData = void 0;
var Event202309GetShopWebhooksResponseData = /** @class */ (function () {
    function Event202309GetShopWebhooksResponseData() {
    }
    Event202309GetShopWebhooksResponseData.getAttributeTypeMap = function () {
        return Event202309GetShopWebhooksResponseData.attributeTypeMap;
    };
    Event202309GetShopWebhooksResponseData.discriminator = undefined;
    Event202309GetShopWebhooksResponseData.attributeTypeMap = [
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        },
        {
            "name": "webhooks",
            "baseName": "webhooks",
            "type": "Array<Event202309GetShopWebhooksResponseDataWebhooks>"
        }
    ];
    return Event202309GetShopWebhooksResponseData;
}());
exports.Event202309GetShopWebhooksResponseData = Event202309GetShopWebhooksResponseData;
