"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202506GetImageTranslationTasksResponseDataTranslationTasks = void 0;
var Product202506GetImageTranslationTasksResponseDataTranslationTasks = /** @class */ (function () {
    function Product202506GetImageTranslationTasksResponseDataTranslationTasks() {
    }
    Product202506GetImageTranslationTasksResponseDataTranslationTasks.getAttributeTypeMap = function () {
        return Product202506GetImageTranslationTasksResponseDataTranslationTasks.attributeTypeMap;
    };
    Product202506GetImageTranslationTasksResponseDataTranslationTasks.discriminator = undefined;
    Product202506GetImageTranslationTasksResponseDataTranslationTasks.attributeTypeMap = [
        {
            "name": "failReason",
            "baseName": "fail_reason",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "originalImage",
            "baseName": "original_image",
            "type": "Product202506GetImageTranslationTasksResponseDataTranslationTasksOriginalImage"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "targetLanguage",
            "baseName": "target_language",
            "type": "string"
        },
        {
            "name": "translatedImage",
            "baseName": "translated_image",
            "type": "Product202506GetImageTranslationTasksResponseDataTranslationTasksTranslatedImage"
        }
    ];
    return Product202506GetImageTranslationTasksResponseDataTranslationTasks;
}());
exports.Product202506GetImageTranslationTasksResponseDataTranslationTasks = Product202506GetImageTranslationTasksResponseDataTranslationTasks;
