"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202506GetImageTranslationTasksResponseDataTranslationTasksTranslatedImage = void 0;
var Product202506GetImageTranslationTasksResponseDataTranslationTasksTranslatedImage = /** @class */ (function () {
    function Product202506GetImageTranslationTasksResponseDataTranslationTasksTranslatedImage() {
    }
    Product202506GetImageTranslationTasksResponseDataTranslationTasksTranslatedImage.getAttributeTypeMap = function () {
        return Product202506GetImageTranslationTasksResponseDataTranslationTasksTranslatedImage.attributeTypeMap;
    };
    Product202506GetImageTranslationTasksResponseDataTranslationTasksTranslatedImage.discriminator = undefined;
    Product202506GetImageTranslationTasksResponseDataTranslationTasksTranslatedImage.attributeTypeMap = [
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }
    ];
    return Product202506GetImageTranslationTasksResponseDataTranslationTasksTranslatedImage;
}());
exports.Product202506GetImageTranslationTasksResponseDataTranslationTasksTranslatedImage = Product202506GetImageTranslationTasksResponseDataTranslationTasksTranslatedImage;
