"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202409CreateManufacturerRequestBody = void 0;
var Product202409CreateManufacturerRequestBody = /** @class */ (function () {
    function Product202409CreateManufacturerRequestBody() {
    }
    Product202409CreateManufacturerRequestBody.getAttributeTypeMap = function () {
        return Product202409CreateManufacturerRequestBody.attributeTypeMap;
    };
    Product202409CreateManufacturerRequestBody.discriminator = undefined;
    Product202409CreateManufacturerRequestBody.attributeTypeMap = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "Product202409CreateManufacturerRequestBodyPhoneNumber"
        },
        {
            "name": "registeredTradeName",
            "baseName": "registered_trade_name",
            "type": "string"
        }
    ];
    return Product202409CreateManufacturerRequestBody;
}());
exports.Product202409CreateManufacturerRequestBody = Product202409CreateManufacturerRequestBody;
