"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202409CreateResponsiblePersonRequestBody = void 0;
var Product202409CreateResponsiblePersonRequestBody = /** @class */ (function () {
    function Product202409CreateResponsiblePersonRequestBody() {
    }
    Product202409CreateResponsiblePersonRequestBody.getAttributeTypeMap = function () {
        return Product202409CreateResponsiblePersonRequestBody.attributeTypeMap;
    };
    Product202409CreateResponsiblePersonRequestBody.discriminator = undefined;
    Product202409CreateResponsiblePersonRequestBody.attributeTypeMap = [
        {
            "name": "address",
            "baseName": "address",
            "type": "Product202409CreateResponsiblePersonRequestBodyAddress"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "Product202409CreateResponsiblePersonRequestBodyPhoneNumber"
        }
    ];
    return Product202409CreateResponsiblePersonRequestBody;
}());
exports.Product202409CreateResponsiblePersonRequestBody = Product202409CreateResponsiblePersonRequestBody;
