"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202409SearchManufacturersResponseDataManufacturersPhoneNumber = void 0;
var Product202409SearchManufacturersResponseDataManufacturersPhoneNumber = /** @class */ (function () {
    function Product202409SearchManufacturersResponseDataManufacturersPhoneNumber() {
    }
    Product202409SearchManufacturersResponseDataManufacturersPhoneNumber.getAttributeTypeMap = function () {
        return Product202409SearchManufacturersResponseDataManufacturersPhoneNumber.attributeTypeMap;
    };
    Product202409SearchManufacturersResponseDataManufacturersPhoneNumber.discriminator = undefined;
    Product202409SearchManufacturersResponseDataManufacturersPhoneNumber.attributeTypeMap = [
        {
            "name": "countryCode",
            "baseName": "country_code",
            "type": "string"
        },
        {
            "name": "localNumber",
            "baseName": "local_number",
            "type": "string"
        }
    ];
    return Product202409SearchManufacturersResponseDataManufacturersPhoneNumber;
}());
exports.Product202409SearchManufacturersResponseDataManufacturersPhoneNumber = Product202409SearchManufacturersResponseDataManufacturersPhoneNumber;
