"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202409SearchManufacturersRequestBody = void 0;
var Product202409SearchManufacturersRequestBody = /** @class */ (function () {
    function Product202409SearchManufacturersRequestBody() {
    }
    Product202409SearchManufacturersRequestBody.getAttributeTypeMap = function () {
        return Product202409SearchManufacturersRequestBody.attributeTypeMap;
    };
    Product202409SearchManufacturersRequestBody.discriminator = undefined;
    Product202409SearchManufacturersRequestBody.attributeTypeMap = [
        {
            "name": "keyword",
            "baseName": "keyword",
            "type": "string"
        },
        {
            "name": "manufacturerIds",
            "baseName": "manufacturer_ids",
            "type": "Array<string>"
        }
    ];
    return Product202409SearchManufacturersRequestBody;
}());
exports.Product202409SearchManufacturersRequestBody = Product202409SearchManufacturersRequestBody;
