"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202409SearchManufacturersResponse = void 0;
var Product202409SearchManufacturersResponse = /** @class */ (function () {
    function Product202409SearchManufacturersResponse() {
    }
    Product202409SearchManufacturersResponse.getAttributeTypeMap = function () {
        return Product202409SearchManufacturersResponse.attributeTypeMap;
    };
    Product202409SearchManufacturersResponse.discriminator = undefined;
    Product202409SearchManufacturersResponse.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Product202409SearchManufacturersResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }
    ];
    return Product202409SearchManufacturersResponse;
}());
exports.Product202409SearchManufacturersResponse = Product202409SearchManufacturersResponse;
