"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202409SearchResponsiblePersonsResponseData = void 0;
var Product202409SearchResponsiblePersonsResponseData = /** @class */ (function () {
    function Product202409SearchResponsiblePersonsResponseData() {
    }
    Product202409SearchResponsiblePersonsResponseData.getAttributeTypeMap = function () {
        return Product202409SearchResponsiblePersonsResponseData.attributeTypeMap;
    };
    Product202409SearchResponsiblePersonsResponseData.discriminator = undefined;
    Product202409SearchResponsiblePersonsResponseData.attributeTypeMap = [
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "responsiblePersons",
            "baseName": "responsible_persons",
            "type": "Array<Product202409SearchResponsiblePersonsResponseDataResponsiblePersons>"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }
    ];
    return Product202409SearchResponsiblePersonsResponseData;
}());
exports.Product202409SearchResponsiblePersonsResponseData = Product202409SearchResponsiblePersonsResponseData;
