"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202409SearchManufacturersResponseDataManufacturers = void 0;
var Product202409SearchManufacturersResponseDataManufacturers = /** @class */ (function () {
    function Product202409SearchManufacturersResponseDataManufacturers() {
    }
    Product202409SearchManufacturersResponseDataManufacturers.getAttributeTypeMap = function () {
        return Product202409SearchManufacturersResponseDataManufacturers.attributeTypeMap;
    };
    Product202409SearchManufacturersResponseDataManufacturers.discriminator = undefined;
    Product202409SearchManufacturersResponseDataManufacturers.attributeTypeMap = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "Product202409SearchManufacturersResponseDataManufacturersPhoneNumber"
        },
        {
            "name": "registeredTradeName",
            "baseName": "registered_trade_name",
            "type": "string"
        }
    ];
    return Product202409SearchManufacturersResponseDataManufacturers;
}());
exports.Product202409SearchManufacturersResponseDataManufacturers = Product202409SearchManufacturersResponseDataManufacturers;
