"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Product202501SearchResponsiblePersonsResponseDataResponsiblePersonsRegionalProfilesAddress = void 0;
var Product202501SearchResponsiblePersonsResponseDataResponsiblePersonsRegionalProfilesAddress = /** @class */ (function () {
    function Product202501SearchResponsiblePersonsResponseDataResponsiblePersonsRegionalProfilesAddress() {
    }
    Product202501SearchResponsiblePersonsResponseDataResponsiblePersonsRegionalProfilesAddress.getAttributeTypeMap = function () {
        return Product202501SearchResponsiblePersonsResponseDataResponsiblePersonsRegionalProfilesAddress.attributeTypeMap;
    };
    Product202501SearchResponsiblePersonsResponseDataResponsiblePersonsRegionalProfilesAddress.discriminator = undefined;
    Product202501SearchResponsiblePersonsResponseDataResponsiblePersonsRegionalProfilesAddress.attributeTypeMap = [
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "district",
            "baseName": "district",
            "type": "string"
        },
        {
            "name": "postalCode",
            "baseName": "postal_code",
            "type": "string"
        },
        {
            "name": "province",
            "baseName": "province",
            "type": "string"
        },
        {
            "name": "streetAddressLine1",
            "baseName": "street_address_line1",
            "type": "string"
        },
        {
            "name": "streetAddressLine2",
            "baseName": "street_address_line2",
            "type": "string"
        }
    ];
    return Product202501SearchResponsiblePersonsResponseDataResponsiblePersonsRegionalProfilesAddress;
}());
exports.Product202501SearchResponsiblePersonsResponseDataResponsiblePersonsRegionalProfilesAddress = Product202501SearchResponsiblePersonsResponseDataResponsiblePersonsRegionalProfilesAddress;
