"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202309CreateActivityRequestBodyDiscountBmsmDiscount = void 0;
var Promotion202309CreateActivityRequestBodyDiscountBmsmDiscount = /** @class */ (function () {
    function Promotion202309CreateActivityRequestBodyDiscountBmsmDiscount() {
    }
    Promotion202309CreateActivityRequestBodyDiscountBmsmDiscount.getAttributeTypeMap = function () {
        return Promotion202309CreateActivityRequestBodyDiscountBmsmDiscount.attributeTypeMap;
    };
    Promotion202309CreateActivityRequestBodyDiscountBmsmDiscount.discriminator = undefined;
    Promotion202309CreateActivityRequestBodyDiscountBmsmDiscount.attributeTypeMap = [
        {
            "name": "details",
            "baseName": "details",
            "type": "Array<Promotion202309CreateActivityRequestBodyDiscountBmsmDiscountDetails>"
        }
    ];
    return Promotion202309CreateActivityRequestBodyDiscountBmsmDiscount;
}());
exports.Promotion202309CreateActivityRequestBodyDiscountBmsmDiscount = Promotion202309CreateActivityRequestBodyDiscountBmsmDiscount;
