"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202309GetActivityResponseDataDiscountBmsmDiscount = void 0;
var Promotion202309GetActivityResponseDataDiscountBmsmDiscount = /** @class */ (function () {
    function Promotion202309GetActivityResponseDataDiscountBmsmDiscount() {
    }
    Promotion202309GetActivityResponseDataDiscountBmsmDiscount.getAttributeTypeMap = function () {
        return Promotion202309GetActivityResponseDataDiscountBmsmDiscount.attributeTypeMap;
    };
    Promotion202309GetActivityResponseDataDiscountBmsmDiscount.discriminator = undefined;
    Promotion202309GetActivityResponseDataDiscountBmsmDiscount.attributeTypeMap = [
        {
            "name": "details",
            "baseName": "details",
            "type": "Array<Promotion202309GetActivityResponseDataDiscountBmsmDiscountDetails>"
        }
    ];
    return Promotion202309GetActivityResponseDataDiscountBmsmDiscount;
}());
exports.Promotion202309GetActivityResponseDataDiscountBmsmDiscount = Promotion202309GetActivityResponseDataDiscountBmsmDiscount;
