"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202309GetActivityResponse = void 0;
var Promotion202309GetActivityResponse = /** @class */ (function () {
    function Promotion202309GetActivityResponse() {
    }
    Promotion202309GetActivityResponse.getAttributeTypeMap = function () {
        return Promotion202309GetActivityResponse.attributeTypeMap;
    };
    Promotion202309GetActivityResponse.discriminator = undefined;
    Promotion202309GetActivityResponse.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Promotion202309GetActivityResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }
    ];
    return Promotion202309GetActivityResponse;
}());
exports.Promotion202309GetActivityResponse = Promotion202309GetActivityResponse;
