"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202309GetActivityResponseDataProductsSkus = void 0;
var Promotion202309GetActivityResponseDataProductsSkus = /** @class */ (function () {
    function Promotion202309GetActivityResponseDataProductsSkus() {
    }
    Promotion202309GetActivityResponseDataProductsSkus.getAttributeTypeMap = function () {
        return Promotion202309GetActivityResponseDataProductsSkus.attributeTypeMap;
    };
    Promotion202309GetActivityResponseDataProductsSkus.discriminator = undefined;
    Promotion202309GetActivityResponseDataProductsSkus.attributeTypeMap = [
        {
            "name": "activityPrice",
            "baseName": "activity_price",
            "type": "Promotion202309GetActivityResponseDataProductsSkusActivityPrice"
        },
        {
            "name": "discount",
            "baseName": "discount",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "quantityLimit",
            "baseName": "quantity_limit",
            "type": "number"
        },
        {
            "name": "quantityPerUser",
            "baseName": "quantity_per_user",
            "type": "number"
        }
    ];
    return Promotion202309GetActivityResponseDataProductsSkus;
}());
exports.Promotion202309GetActivityResponseDataProductsSkus = Promotion202309GetActivityResponseDataProductsSkus;
