"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202309GetActivityResponseDataDiscount = void 0;
var Promotion202309GetActivityResponseDataDiscount = /** @class */ (function () {
    function Promotion202309GetActivityResponseDataDiscount() {
    }
    Promotion202309GetActivityResponseDataDiscount.getAttributeTypeMap = function () {
        return Promotion202309GetActivityResponseDataDiscount.attributeTypeMap;
    };
    Promotion202309GetActivityResponseDataDiscount.discriminator = undefined;
    Promotion202309GetActivityResponseDataDiscount.attributeTypeMap = [
        {
            "name": "bmsmDiscount",
            "baseName": "bmsm_discount",
            "type": "Promotion202309GetActivityResponseDataDiscountBmsmDiscount"
        },
        {
            "name": "shippingDiscount",
            "baseName": "shipping_discount",
            "type": "Promotion202309GetActivityResponseDataDiscountShippingDiscount"
        }
    ];
    return Promotion202309GetActivityResponseDataDiscount;
}());
exports.Promotion202309GetActivityResponseDataDiscount = Promotion202309GetActivityResponseDataDiscount;
