"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202309GetActivityResponseDataProductsSkusActivityPrice = void 0;
var Promotion202309GetActivityResponseDataProductsSkusActivityPrice = /** @class */ (function () {
    function Promotion202309GetActivityResponseDataProductsSkusActivityPrice() {
    }
    Promotion202309GetActivityResponseDataProductsSkusActivityPrice.getAttributeTypeMap = function () {
        return Promotion202309GetActivityResponseDataProductsSkusActivityPrice.attributeTypeMap;
    };
    Promotion202309GetActivityResponseDataProductsSkusActivityPrice.discriminator = undefined;
    Promotion202309GetActivityResponseDataProductsSkusActivityPrice.attributeTypeMap = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        }
    ];
    return Promotion202309GetActivityResponseDataProductsSkusActivityPrice;
}());
exports.Promotion202309GetActivityResponseDataProductsSkusActivityPrice = Promotion202309GetActivityResponseDataProductsSkusActivityPrice;
