"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202309GetActivityResponseDataProducts = void 0;
var Promotion202309GetActivityResponseDataProducts = /** @class */ (function () {
    function Promotion202309GetActivityResponseDataProducts() {
    }
    Promotion202309GetActivityResponseDataProducts.getAttributeTypeMap = function () {
        return Promotion202309GetActivityResponseDataProducts.attributeTypeMap;
    };
    Promotion202309GetActivityResponseDataProducts.discriminator = undefined;
    Promotion202309GetActivityResponseDataProducts.attributeTypeMap = [
        {
            "name": "activityPrice",
            "baseName": "activity_price",
            "type": "Promotion202309GetActivityResponseDataProductsActivityPrice"
        },
        {
            "name": "discount",
            "baseName": "discount",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "quantityLimit",
            "baseName": "quantity_limit",
            "type": "number"
        },
        {
            "name": "quantityPerUser",
            "baseName": "quantity_per_user",
            "type": "number"
        },
        {
            "name": "skus",
            "baseName": "skus",
            "type": "Array<Promotion202309GetActivityResponseDataProductsSkus>"
        }
    ];
    return Promotion202309GetActivityResponseDataProducts;
}());
exports.Promotion202309GetActivityResponseDataProducts = Promotion202309GetActivityResponseDataProducts;
