"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202309RemoveActivityProductRequestBody = void 0;
var Promotion202309RemoveActivityProductRequestBody = /** @class */ (function () {
    function Promotion202309RemoveActivityProductRequestBody() {
    }
    Promotion202309RemoveActivityProductRequestBody.getAttributeTypeMap = function () {
        return Promotion202309RemoveActivityProductRequestBody.attributeTypeMap;
    };
    Promotion202309RemoveActivityProductRequestBody.discriminator = undefined;
    Promotion202309RemoveActivityProductRequestBody.attributeTypeMap = [
        {
            "name": "productIds",
            "baseName": "product_ids",
            "type": "Array<string>"
        },
        {
            "name": "skuIds",
            "baseName": "sku_ids",
            "type": "Array<string>"
        }
    ];
    return Promotion202309RemoveActivityProductRequestBody;
}());
exports.Promotion202309RemoveActivityProductRequestBody = Promotion202309RemoveActivityProductRequestBody;
