"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202309SearchActivitiesResponseDataActivitiesDiscountShippingDiscount = void 0;
var Promotion202309SearchActivitiesResponseDataActivitiesDiscountShippingDiscount = /** @class */ (function () {
    function Promotion202309SearchActivitiesResponseDataActivitiesDiscountShippingDiscount() {
    }
    Promotion202309SearchActivitiesResponseDataActivitiesDiscountShippingDiscount.getAttributeTypeMap = function () {
        return Promotion202309SearchActivitiesResponseDataActivitiesDiscountShippingDiscount.attributeTypeMap;
    };
    Promotion202309SearchActivitiesResponseDataActivitiesDiscountShippingDiscount.discriminator = undefined;
    Promotion202309SearchActivitiesResponseDataActivitiesDiscountShippingDiscount.attributeTypeMap = [
        {
            "name": "areaScope",
            "baseName": "area_scope",
            "type": "Promotion202309SearchActivitiesResponseDataActivitiesDiscountShippingDiscountAreaScope"
        },
        {
            "name": "inventoryType",
            "baseName": "inventory_type",
            "type": "string"
        },
        {
            "name": "shippingMethod",
            "baseName": "shipping_method",
            "type": "string"
        },
        {
            "name": "thresholdType",
            "baseName": "threshold_type",
            "type": "string"
        },
        {
            "name": "thresholdValue",
            "baseName": "threshold_value",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }
    ];
    return Promotion202309SearchActivitiesResponseDataActivitiesDiscountShippingDiscount;
}());
exports.Promotion202309SearchActivitiesResponseDataActivitiesDiscountShippingDiscount = Promotion202309SearchActivitiesResponseDataActivitiesDiscountShippingDiscount;
