"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202309SearchActivitiesResponseDataActivitiesDiscountBmsmDiscountDetails = void 0;
var Promotion202309SearchActivitiesResponseDataActivitiesDiscountBmsmDiscountDetails = /** @class */ (function () {
    function Promotion202309SearchActivitiesResponseDataActivitiesDiscountBmsmDiscountDetails() {
    }
    Promotion202309SearchActivitiesResponseDataActivitiesDiscountBmsmDiscountDetails.getAttributeTypeMap = function () {
        return Promotion202309SearchActivitiesResponseDataActivitiesDiscountBmsmDiscountDetails.attributeTypeMap;
    };
    Promotion202309SearchActivitiesResponseDataActivitiesDiscountBmsmDiscountDetails.discriminator = undefined;
    Promotion202309SearchActivitiesResponseDataActivitiesDiscountBmsmDiscountDetails.attributeTypeMap = [
        {
            "name": "thresholdType",
            "baseName": "threshold_type",
            "type": "string"
        },
        {
            "name": "thresholdValue",
            "baseName": "threshold_value",
            "type": "string"
        },
        {
            "name": "tier",
            "baseName": "tier",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }
    ];
    return Promotion202309SearchActivitiesResponseDataActivitiesDiscountBmsmDiscountDetails;
}());
exports.Promotion202309SearchActivitiesResponseDataActivitiesDiscountBmsmDiscountDetails = Promotion202309SearchActivitiesResponseDataActivitiesDiscountBmsmDiscountDetails;
