"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202309SearchActivitiesResponseDataActivitiesDiscount = void 0;
var Promotion202309SearchActivitiesResponseDataActivitiesDiscount = /** @class */ (function () {
    function Promotion202309SearchActivitiesResponseDataActivitiesDiscount() {
    }
    Promotion202309SearchActivitiesResponseDataActivitiesDiscount.getAttributeTypeMap = function () {
        return Promotion202309SearchActivitiesResponseDataActivitiesDiscount.attributeTypeMap;
    };
    Promotion202309SearchActivitiesResponseDataActivitiesDiscount.discriminator = undefined;
    Promotion202309SearchActivitiesResponseDataActivitiesDiscount.attributeTypeMap = [
        {
            "name": "bmsmDiscount",
            "baseName": "bmsm_discount",
            "type": "Promotion202309SearchActivitiesResponseDataActivitiesDiscountBmsmDiscount"
        },
        {
            "name": "shippingDiscount",
            "baseName": "shipping_discount",
            "type": "Promotion202309SearchActivitiesResponseDataActivitiesDiscountShippingDiscount"
        }
    ];
    return Promotion202309SearchActivitiesResponseDataActivitiesDiscount;
}());
exports.Promotion202309SearchActivitiesResponseDataActivitiesDiscount = Promotion202309SearchActivitiesResponseDataActivitiesDiscount;
