"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202309UpdateActivityProductResponseData = void 0;
var Promotion202309UpdateActivityProductResponseData = /** @class */ (function () {
    function Promotion202309UpdateActivityProductResponseData() {
    }
    Promotion202309UpdateActivityProductResponseData.getAttributeTypeMap = function () {
        return Promotion202309UpdateActivityProductResponseData.attributeTypeMap;
    };
    Promotion202309UpdateActivityProductResponseData.discriminator = undefined;
    Promotion202309UpdateActivityProductResponseData.attributeTypeMap = [
        {
            "name": "activityId",
            "baseName": "activity_id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        },
        {
            "name": "updateTime",
            "baseName": "update_time",
            "type": "number"
        }
    ];
    return Promotion202309UpdateActivityProductResponseData;
}());
exports.Promotion202309UpdateActivityProductResponseData = Promotion202309UpdateActivityProductResponseData;
