"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202309UpdateActivityProductRequestBodyProductsSkus = void 0;
var Promotion202309UpdateActivityProductRequestBodyProductsSkus = /** @class */ (function () {
    function Promotion202309UpdateActivityProductRequestBodyProductsSkus() {
    }
    Promotion202309UpdateActivityProductRequestBodyProductsSkus.getAttributeTypeMap = function () {
        return Promotion202309UpdateActivityProductRequestBodyProductsSkus.attributeTypeMap;
    };
    Promotion202309UpdateActivityProductRequestBodyProductsSkus.discriminator = undefined;
    Promotion202309UpdateActivityProductRequestBodyProductsSkus.attributeTypeMap = [
        {
            "name": "activityPriceAmount",
            "baseName": "activity_price_amount",
            "type": "string"
        },
        {
            "name": "discount",
            "baseName": "discount",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "quantityLimit",
            "baseName": "quantity_limit",
            "type": "number"
        },
        {
            "name": "quantityPerUser",
            "baseName": "quantity_per_user",
            "type": "number"
        }
    ];
    return Promotion202309UpdateActivityProductRequestBodyProductsSkus;
}());
exports.Promotion202309UpdateActivityProductRequestBodyProductsSkus = Promotion202309UpdateActivityProductRequestBodyProductsSkus;
