"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202309UpdateActivityProductResponse = void 0;
var Promotion202309UpdateActivityProductResponse = /** @class */ (function () {
    function Promotion202309UpdateActivityProductResponse() {
    }
    Promotion202309UpdateActivityProductResponse.getAttributeTypeMap = function () {
        return Promotion202309UpdateActivityProductResponse.attributeTypeMap;
    };
    Promotion202309UpdateActivityProductResponse.discriminator = undefined;
    Promotion202309UpdateActivityProductResponse.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Promotion202309UpdateActivityProductResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }
    ];
    return Promotion202309UpdateActivityProductResponse;
}());
exports.Promotion202309UpdateActivityProductResponse = Promotion202309UpdateActivityProductResponse;
