"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202309UpdateActivityRequestBodyDiscountBmsmDiscount = void 0;
var Promotion202309UpdateActivityRequestBodyDiscountBmsmDiscount = /** @class */ (function () {
    function Promotion202309UpdateActivityRequestBodyDiscountBmsmDiscount() {
    }
    Promotion202309UpdateActivityRequestBodyDiscountBmsmDiscount.getAttributeTypeMap = function () {
        return Promotion202309UpdateActivityRequestBodyDiscountBmsmDiscount.attributeTypeMap;
    };
    Promotion202309UpdateActivityRequestBodyDiscountBmsmDiscount.discriminator = undefined;
    Promotion202309UpdateActivityRequestBodyDiscountBmsmDiscount.attributeTypeMap = [
        {
            "name": "details",
            "baseName": "details",
            "type": "Array<Promotion202309UpdateActivityRequestBodyDiscountBmsmDiscountDetails>"
        }
    ];
    return Promotion202309UpdateActivityRequestBodyDiscountBmsmDiscount;
}());
exports.Promotion202309UpdateActivityRequestBodyDiscountBmsmDiscount = Promotion202309UpdateActivityRequestBodyDiscountBmsmDiscount;
