"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202406GetCouponResponseDataCouponThreshold = void 0;
var Promotion202406GetCouponResponseDataCouponThreshold = /** @class */ (function () {
    function Promotion202406GetCouponResponseDataCouponThreshold() {
    }
    Promotion202406GetCouponResponseDataCouponThreshold.getAttributeTypeMap = function () {
        return Promotion202406GetCouponResponseDataCouponThreshold.attributeTypeMap;
    };
    Promotion202406GetCouponResponseDataCouponThreshold.discriminator = undefined;
    Promotion202406GetCouponResponseDataCouponThreshold.attributeTypeMap = [
        {
            "name": "minSpend",
            "baseName": "min_spend",
            "type": "Promotion202406GetCouponResponseDataCouponThresholdMinSpend"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }
    ];
    return Promotion202406GetCouponResponseDataCouponThreshold;
}());
exports.Promotion202406GetCouponResponseDataCouponThreshold = Promotion202406GetCouponResponseDataCouponThreshold;
