"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202406GetCouponResponseDataCouponDiscountReductionAmount = void 0;
var Promotion202406GetCouponResponseDataCouponDiscountReductionAmount = /** @class */ (function () {
    function Promotion202406GetCouponResponseDataCouponDiscountReductionAmount() {
    }
    Promotion202406GetCouponResponseDataCouponDiscountReductionAmount.getAttributeTypeMap = function () {
        return Promotion202406GetCouponResponseDataCouponDiscountReductionAmount.attributeTypeMap;
    };
    Promotion202406GetCouponResponseDataCouponDiscountReductionAmount.discriminator = undefined;
    Promotion202406GetCouponResponseDataCouponDiscountReductionAmount.attributeTypeMap = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        }
    ];
    return Promotion202406GetCouponResponseDataCouponDiscountReductionAmount;
}());
exports.Promotion202406GetCouponResponseDataCouponDiscountReductionAmount = Promotion202406GetCouponResponseDataCouponDiscountReductionAmount;
