"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202406GetCouponResponseDataCouponRedemptionDuration = void 0;
var Promotion202406GetCouponResponseDataCouponRedemptionDuration = /** @class */ (function () {
    function Promotion202406GetCouponResponseDataCouponRedemptionDuration() {
    }
    Promotion202406GetCouponResponseDataCouponRedemptionDuration.getAttributeTypeMap = function () {
        return Promotion202406GetCouponResponseDataCouponRedemptionDuration.attributeTypeMap;
    };
    Promotion202406GetCouponResponseDataCouponRedemptionDuration.discriminator = undefined;
    Promotion202406GetCouponResponseDataCouponRedemptionDuration.attributeTypeMap = [
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "number"
        },
        {
            "name": "relativeTime",
            "baseName": "relative_time",
            "type": "number"
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }
    ];
    return Promotion202406GetCouponResponseDataCouponRedemptionDuration;
}());
exports.Promotion202406GetCouponResponseDataCouponRedemptionDuration = Promotion202406GetCouponResponseDataCouponRedemptionDuration;
