"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202406GetCouponResponseDataCouponUsageLimits = void 0;
var Promotion202406GetCouponResponseDataCouponUsageLimits = /** @class */ (function () {
    function Promotion202406GetCouponResponseDataCouponUsageLimits() {
    }
    Promotion202406GetCouponResponseDataCouponUsageLimits.getAttributeTypeMap = function () {
        return Promotion202406GetCouponResponseDataCouponUsageLimits.attributeTypeMap;
    };
    Promotion202406GetCouponResponseDataCouponUsageLimits.discriminator = undefined;
    Promotion202406GetCouponResponseDataCouponUsageLimits.attributeTypeMap = [
        {
            "name": "redemptionLimit",
            "baseName": "redemption_limit",
            "type": "number"
        },
        {
            "name": "singleBuyerClaimLimit",
            "baseName": "single_buyer_claim_limit",
            "type": "number"
        },
        {
            "name": "totalClaimLimit",
            "baseName": "total_claim_limit",
            "type": "number"
        }
    ];
    return Promotion202406GetCouponResponseDataCouponUsageLimits;
}());
exports.Promotion202406GetCouponResponseDataCouponUsageLimits = Promotion202406GetCouponResponseDataCouponUsageLimits;
