"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202406SearchCouponsResponse = void 0;
var Promotion202406SearchCouponsResponse = /** @class */ (function () {
    function Promotion202406SearchCouponsResponse() {
    }
    Promotion202406SearchCouponsResponse.getAttributeTypeMap = function () {
        return Promotion202406SearchCouponsResponse.attributeTypeMap;
    };
    Promotion202406SearchCouponsResponse.discriminator = undefined;
    Promotion202406SearchCouponsResponse.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Promotion202406SearchCouponsResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }
    ];
    return Promotion202406SearchCouponsResponse;
}());
exports.Promotion202406SearchCouponsResponse = Promotion202406SearchCouponsResponse;
