"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Promotion202406SearchCouponsResponseData = void 0;
var Promotion202406SearchCouponsResponseData = /** @class */ (function () {
    function Promotion202406SearchCouponsResponseData() {
    }
    Promotion202406SearchCouponsResponseData.getAttributeTypeMap = function () {
        return Promotion202406SearchCouponsResponseData.attributeTypeMap;
    };
    Promotion202406SearchCouponsResponseData.discriminator = undefined;
    Promotion202406SearchCouponsResponseData.attributeTypeMap = [
        {
            "name": "coupons",
            "baseName": "coupons",
            "type": "Array<Promotion202406SearchCouponsResponseDataCoupons>"
        },
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }
    ];
    return Promotion202406SearchCouponsResponseData;
}());
exports.Promotion202406SearchCouponsResponseData = Promotion202406SearchCouponsResponseData;
