"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Finance202309GetPaymentsResponseDataPaymentsSettlementAmount = void 0;
var Finance202309GetPaymentsResponseDataPaymentsSettlementAmount = /** @class */ (function () {
    function Finance202309GetPaymentsResponseDataPaymentsSettlementAmount() {
    }
    Finance202309GetPaymentsResponseDataPaymentsSettlementAmount.getAttributeTypeMap = function () {
        return Finance202309GetPaymentsResponseDataPaymentsSettlementAmount.attributeTypeMap;
    };
    Finance202309GetPaymentsResponseDataPaymentsSettlementAmount.discriminator = undefined;
    Finance202309GetPaymentsResponseDataPaymentsSettlementAmount.attributeTypeMap = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }
    ];
    return Finance202309GetPaymentsResponseDataPaymentsSettlementAmount;
}());
exports.Finance202309GetPaymentsResponseDataPaymentsSettlementAmount = Finance202309GetPaymentsResponseDataPaymentsSettlementAmount;
