"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Finance202309GetStatementsResponseData = void 0;
var Finance202309GetStatementsResponseData = /** @class */ (function () {
    function Finance202309GetStatementsResponseData() {
    }
    Finance202309GetStatementsResponseData.getAttributeTypeMap = function () {
        return Finance202309GetStatementsResponseData.attributeTypeMap;
    };
    Finance202309GetStatementsResponseData.discriminator = undefined;
    Finance202309GetStatementsResponseData.attributeTypeMap = [
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "statements",
            "baseName": "statements",
            "type": "Array<Finance202309GetStatementsResponseDataStatements>"
        }
    ];
    return Finance202309GetStatementsResponseData;
}());
exports.Finance202309GetStatementsResponseData = Finance202309GetStatementsResponseData;
