"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Finance202309GetStatementsResponseDataStatements = void 0;
var Finance202309GetStatementsResponseDataStatements = /** @class */ (function () {
    function Finance202309GetStatementsResponseDataStatements() {
    }
    Finance202309GetStatementsResponseDataStatements.getAttributeTypeMap = function () {
        return Finance202309GetStatementsResponseDataStatements.attributeTypeMap;
    };
    Finance202309GetStatementsResponseDataStatements.discriminator = undefined;
    Finance202309GetStatementsResponseDataStatements.attributeTypeMap = [
        {
            "name": "adjustmentAmount",
            "baseName": "adjustment_amount",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "feeAmount",
            "baseName": "fee_amount",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "netSalesAmount",
            "baseName": "net_sales_amount",
            "type": "string"
        },
        {
            "name": "paymentId",
            "baseName": "payment_id",
            "type": "string"
        },
        {
            "name": "paymentStatus",
            "baseName": "payment_status",
            "type": "string"
        },
        {
            "name": "revenueAmount",
            "baseName": "revenue_amount",
            "type": "string"
        },
        {
            "name": "settlementAmount",
            "baseName": "settlement_amount",
            "type": "string"
        },
        {
            "name": "shippingCostAmount",
            "baseName": "shipping_cost_amount",
            "type": "string"
        },
        {
            "name": "statementTime",
            "baseName": "statement_time",
            "type": "number"
        }
    ];
    return Finance202309GetStatementsResponseDataStatements;
}());
exports.Finance202309GetStatementsResponseDataStatements = Finance202309GetStatementsResponseDataStatements;
