"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Finance202309GetTransactionsbyStatementResponse = void 0;
var Finance202309GetTransactionsbyStatementResponse = /** @class */ (function () {
    function Finance202309GetTransactionsbyStatementResponse() {
    }
    Finance202309GetTransactionsbyStatementResponse.getAttributeTypeMap = function () {
        return Finance202309GetTransactionsbyStatementResponse.attributeTypeMap;
    };
    Finance202309GetTransactionsbyStatementResponse.discriminator = undefined;
    Finance202309GetTransactionsbyStatementResponse.attributeTypeMap = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Finance202309GetTransactionsbyStatementResponseData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        }
    ];
    return Finance202309GetTransactionsbyStatementResponse;
}());
exports.Finance202309GetTransactionsbyStatementResponse = Finance202309GetTransactionsbyStatementResponse;
