"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Finance202309GetWithdrawalsResponseData = void 0;
var Finance202309GetWithdrawalsResponseData = /** @class */ (function () {
    function Finance202309GetWithdrawalsResponseData() {
    }
    Finance202309GetWithdrawalsResponseData.getAttributeTypeMap = function () {
        return Finance202309GetWithdrawalsResponseData.attributeTypeMap;
    };
    Finance202309GetWithdrawalsResponseData.discriminator = undefined;
    Finance202309GetWithdrawalsResponseData.attributeTypeMap = [
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        },
        {
            "name": "withdrawals",
            "baseName": "withdrawals",
            "type": "Array<Finance202309GetWithdrawalsResponseDataWithdrawals>"
        }
    ];
    return Finance202309GetWithdrawalsResponseData;
}());
exports.Finance202309GetWithdrawalsResponseData = Finance202309GetWithdrawalsResponseData;
