"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.DataReconciliation202401QualityFactoryOrderDataImportAPIResponseData = void 0;
var DataReconciliation202401QualityFactoryOrderDataImportAPIResponseData = /** @class */ (function () {
    function DataReconciliation202401QualityFactoryOrderDataImportAPIResponseData() {
    }
    DataReconciliation202401QualityFactoryOrderDataImportAPIResponseData.getAttributeTypeMap = function () {
        return DataReconciliation202401QualityFactoryOrderDataImportAPIResponseData.attributeTypeMap;
    };
    DataReconciliation202401QualityFactoryOrderDataImportAPIResponseData.discriminator = undefined;
    DataReconciliation202401QualityFactoryOrderDataImportAPIResponseData.attributeTypeMap = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrors>"
        }
    ];
    return DataReconciliation202401QualityFactoryOrderDataImportAPIResponseData;
}());
exports.DataReconciliation202401QualityFactoryOrderDataImportAPIResponseData = DataReconciliation202401QualityFactoryOrderDataImportAPIResponseData;
