"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages = void 0;
var DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages = /** @class */ (function () {
    function DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages() {
    }
    DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages.getAttributeTypeMap = function () {
        return DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages.attributeTypeMap;
    };
    DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages.discriminator = undefined;
    DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages.attributeTypeMap = [
        {
            "name": "packageId",
            "baseName": "package_id",
            "type": "string"
        },
        {
            "name": "shippingProviderName",
            "baseName": "shipping_provider_name",
            "type": "string"
        },
        {
            "name": "trackingNumber",
            "baseName": "tracking_number",
            "type": "string"
        }
    ];
    return DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages;
}());
exports.DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages = DataReconciliation202401QualityFactoryOrderDataImportAPIRequestBodyOrdersPackages;
