"use strict";
/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetail = void 0;
var DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetail = /** @class */ (function () {
    function DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetail() {
    }
    DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetail.getAttributeTypeMap = function () {
        return DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetail.attributeTypeMap;
    };
    DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetail.discriminator = undefined;
    DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetail.attributeTypeMap = [
        {
            "name": "channelOrderId",
            "baseName": "channel_order_id",
            "type": "string"
        },
        {
            "name": "channelType",
            "baseName": "channel_type",
            "type": "string"
        },
        {
            "name": "extraErrors",
            "baseName": "extra_errors",
            "type": "Array<DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetailExtraErrors>"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        }
    ];
    return DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetail;
}());
exports.DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetail = DataReconciliation202401QualityFactoryOrderDataImportAPIResponseDataErrorsDetail;
